### ISSUE TITLE
"Update" link styling inconsistent

### ISSUE THREAD

**Issue by atreni** [ctoec/ecis-experimental#1007]
Inconsistent with link styling used on Roster
<img width="1021" alt="Screen Shot 2020-04-28 at 8 47 10 AM" src="https://user-images.githubusercontent.com/7797826/80489417-caf7ea00-892d-11ea-9cdc-45cb1d168807.png">

**Comment by RyanHansz** [comment]
Copying from an old QA comment:
On a child record, edit links are missing styling (hover states and blue color of #005ea2) and are meant to align to the section header:

<img width="918" alt="Screen Shot 2020-04-28 at 10 09 37 AM" src="https://user-images.githubusercontent.com/63253539/80497393-61310d80-8938-11ea-8674-a12bba26a3e3.png">
