### ISSUE TITLE
Updating designs based on usability testing results

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#101]

**Comment by atreni** [comment]
Roster: 
- Funding tags + connect with enrollment type (part time/full time)
- Legend 
- Remove CDC monthly
- Sub nav visuals indicator
Reports:
- Remove “past due” indicator and change to red date
- Alerts Logic and visuals (all)
- Reports indicator alert: 2 weeks before report is due (1-15) (15-31 - no alert)
Enrollment flow:
- Move C4K to Enrollment/funding as additional funding source
- QA of Enrollment flow and Summary page (HOLD)
