### ISSUE TITLE
Week of 10/14-10/19 Usability Testing

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#102]

**Comment by victoriasuwardiman** [comment]
Usability Testing Schedule:
10/15 - 10am
10/16 - 2pm
10/17 - 1pm
10/18 - 10:30am

**Comment by victoriasuwardiman** [comment]
Report from week of 10/15-10/18 usability testing: https://drive.google.com/open?id=1-YNc0eKL4E-UsiEMoYuNk4QBCWfhn9nQRCmPi9jqcBk
