### ISSUE TITLE
Only allow users to edit non-ended C4K certs

### ISSUE THREAD

**Issue by cailyncodes** [ctoec/ecis-experimental#1021]
Currently, when a user edits an enrollments with a child with multiple c4k certificates the UI arbitrarily selects between the multiple certificates.

As a user, I want to only be able to edit the c4k certificate for a child that does not have an end date.

AC: The enrollment and funding edit form populates with the c4k certificate with no end date. If all certificates have end dates, that is functionally the same as having no c4k certificates.

Assumptions: At most one c4k certificates has no end date.

**Comment by jlhogan** [comment]
with fundings, we achieve this by using a `getCurrentCDCFunding` helper, which returns the funding w no end date. Doing something similar for `getCurrentC4KCert` would make sense to me!
