### ISSUE TITLE
Using the default income redetermination date results in a missing field after submit

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/ecis-experimental#1033]
Blocked

If I use the default date for an income redetermination (today's date) after submitting the new redetermination will show the field as missing. 
<img width="987" alt="Screen Shot 2020-05-04 at 5 44 51 PM" src="https://user-images.githubusercontent.com/63253539/81016726-fc415000-8e2e-11ea-87ba-5f0d1af10e60.png">
![defaultdatebug](https://user-images.githubusercontent.com/63253539/81016902-53472500-8e2f-11ea-8954-895c34d9e771.gif)

**Comment by julyytran** [comment]
closing since we are no longer doing a default date
