### ISSUE TITLE
Switching from "income not disclosed" back to filled out family income determination info does not reshow the CDC funding option

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/ecis-experimental#1084]
1. Enroll new child
2. In Family Income Determination, select "income not disclosed"
3. Save
4. In Enrollment and Funding, see that only Private Pay is available
5. Edit Family Income Determination, uncheck "income not disclosed" and fill in fields
6. Save
7. See that Private Pay is still the only option available

![image](https://user-images.githubusercontent.com/51121888/81826907-4220a700-9506-11ea-87f2-614b3a66c896.png)

**Comment by cailyncodes** [comment]
@victoriasuwardiman I think this is expected behavior. There is no age group selected, so we cannot show the available funding slots until that point. I think this was discussed before and this is what we decided. Perhaps we revisit it, though

**Comment by victoriasuwardiman** [comment]
Oh that makes sense! Maybe as an enhancement we can consider exposing options as they're needed (not exposing funding type until age group is selected). I'll add to design board and close this!
