### ISSUE TITLE
Can't see/update missing info on child record

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/ecis-experimental#1085]
In staging, Alan Rickman is labeled as having missing info. When I go to update his info, nothing appears to be missing.
<img width="1072" alt="Screen Shot 2020-05-13 at 10 44 12 AM" src="https://user-images.githubusercontent.com/63253539/81827640-f4586e80-9506-11ea-8216-caae778c7276.png">

**Comment by jlhogan** [comment]
validation error on child: 
```
field: "C4KFamilyCaseNumber"
fields: null
isSubObjectValidation: false
message: "C4K Family Case Number is required when child has c4k funding"
```
fix options:
- make this `isSubObjectValidation: true`
- do special handling in front end child form status func to ignore errors for this field

**Comment by cailyncodes** [comment]
With this ticket, I am also going to clean up our front-end validation utils
