### ISSUE TITLE
I can export my report to CSV

### ISSUE THREAD

**Issue by julyytran** [ctoec/ecis-experimental#1091]
As a provider, I can export my submitted reports to CSV so that I can share and use the data for other purposes, such as sharing with stakeholders and auditors.

When I click on the export icon on the Reports page or when I click on "Export Report" in a report, the data in that report is downloaded to my computer as a CSV. [Designs with export button](https://share.goabstract.com/735b5928-abe5-4e0f-b87a-0b0f7d5b6a24)

The CSV is formatted following this [CDC Export Template](https://docs.google.com/spreadsheets/d/1wuXcoaQnCyJHQomKyECKklDaWER0KWtAJ3115SKyQk4/edit#gid=600449094
).

**Comment by jlhogan** [comment]
Can someone share the svg for file download icon?

**Comment by julyytran** [comment]
@RyanHansz Could you share the SVG?
