### ISSUE TITLE
Deprecate `include` QS param in all controller functions

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#1138]
**context**: organization, report, enrollment, site controller functions all have query string parameter `include` which enables API client to dynamically request the data they want. This is an over abstraction. Each controller endpoint is only ever used to request the same data object with the same field. 

**AC**:
- repository functions that accept `include` as a QS parameter are refactored to  return the appropriate response shape 
  - organization:
    - `GetOrganizationById` returns organization with FundingSpaces, Sites, and Site.Enrollments 
  - enrollment
    - `GetEnrollmentsForSiteAsync returns enrollments as defined in `EnrollmentSummaryDTO`
    - `GetEnrollmentsForOrganizationAsync` returns enrollments as defined in `EnrollmentSummaryDTO`
    - `GetEnrollmentForSiteAsync` returns enrollment as defined in `EnrollmentDTO`
  - reports
    - `GetReportsForOrganization` returns reports as defined in `OrganizationReportSummaryDTO`
    - `GetReportForOrganizationAsync` returns report as defined in `CdcReportDTO` (and should be rewritten as a blocking, not async, function) 
  - sites
    - `GetSiteForOrganizationAsync` returns site with Enrollments, Enrollment.Fundings, Organization, and Organization.FundingSpaces
- Organizations, sites, reports, enrollments controller function should be refactored to remove the `include` QS param and call appropriate repository functions

**Comment by cailyncodes** [comment]
Closed by #1169
