### ISSUE TITLE
If I save a child with only first and last name, I can't go back and add CDC funding later

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#1204]
If I save a child with only first and last name, I can't go back and add CDC funding later

**Comment by jlhogan** [comment]
well is this a bug, or just that https://github.com/ctoec/ecis-experimental/issues/1157 is not implemented yet?

**Comment by mmazanec22** [comment]
Oh def the latter, sorry for the duplicate!
