### ISSUE TITLE
Enrollment detail needs to be loaded earlier for batch edit description

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#1207]
~Even though we're creating an empty family in the family info section, it doesn't save when you press save.  Potentially user is not defined yet when we're trying to get the org id?~

We're setting the description before making the enrollment detail get request, so it doesn't include family or sub objects when it first loads.  Fix is to include enrollment details on initial get for enrollments or make a separate endpoint.

**Comment by cailyncodes** [comment]
@mmazanec22  I don't think I can repo this. Do you have steps beyond just going through a new enrollment flow?

**Comment by mmazanec22** [comment]
Renaming and assigning to myself as title is misleading and this is related to the work I did on #1200
