### ISSUE TITLE
TextInput component

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#130]
**Story:** As a developer, I want to be able to build forms with Text Input controls, per the [USWDS](https://designsystem.digital.gov/components/form-controls/#text-input).

The [CMS Design System](https://design.cms.gov), which is implemented in React, may be a useful reference.

**AC:**

* A React component, matching the USWDS, is available in the Storybook.
* When the control is focused, it displays a blue border.
* If the text entered is invalid, a warning state highlights the offending control, and a warning message informs the user what needs to be done to correct the problem.
* We do not currently have plans for the success state. Including this state is optional.

<img width="425" alt="Screen Shot 2019-10-21 at 8 03 48 AM" src="https://user-images.githubusercontent.com/5375557/67209455-fdec7e80-f3dc-11e9-8263-dbc51b29a2fe.png">

**Comment by cailyncodes** [comment]
Closed by #166
