### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#131]
**Story:** As a developer, I want to be able to build forms with Dropdown controls, per the [USWDS](https://designsystem.digital.gov/components/form-controls/#dropdown).

The [CMS Design System](https://design.cms.gov), which is implemented in React, may be a useful reference.

**AC:**

* A React component, matching the USWDS, is available in the Storybook.
* The control can be manipulated from the keyboard alone.
* If the selected option is invalid, a warning state highlights the offending control, and a warning message informs the user what needs to be done to correct the problem.

<img width="286" alt="Screen Shot 2019-10-21 at 8 09 18 AM" src="https://user-images.githubusercontent.com/5375557/67209691-70f5f500-f3dd-11e9-92c9-f472731358d2.png">

**Comment by cailyncodes** [comment]
Closed by #201
