### ISSUE TITLE
Validation of models

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#134]
**Story:** As an OEC stakeholder, I want to define rules that flag obviously bad data to providers, or that require certain information to be entered before a report can be submitted, or that require information to be updated on a regular cadence.

**Tech discussion**

**Different types of rules.** Here's an interesting scenario: Sometimes providers will want to enter a child into the system, but they don't yet have all the information. Let's say they don't have the kid's address. Now address is a "required" field. We want to ensure that any kid receiving funding has that info. But we also want someone to be able to enter the information they have, and come back to it.

This leads me to conclude we probably need a two-tier validation system.

* Some rules prevent saving information. I shouldn't be able to say a kid was born in 1915. If I try to save a kid with that birthday, I'll be barred from going any further until I correct that mistake.
* Some rules allow the information to be saved, but show a warning, and would prevent submitting a report including that information. The required address scenario above would be an example. Requiring an income determination in the last 12 months is another example.

When we run the warning rules, we should also run the hard and fast rules. This would support adding a new rule that existing data violates. The data was valid at the time it was saved, but now you'll need to correct it before you can submit any reports using it.

**Server-side vs. client-side.** Ideally, we would only write rules once. With this constraint (and the possibility of API access in the future), I think the only place to perform validation is on the server side.

The API, both when fetching data and when mutating it, should be capable of returning a list of issues with a record. This would allow the UI to flag records that need some sort of action, and during data entry flows, highlight fields with known errors.

**Developer ergonomics.** Today in ECIS, all such rules are buried in a ginormous file called BusinessRules.cs. Rules call out to other rules. It's a mess. Let's not do the same.

I'd love an interface such that each rule is its own class, lives in its own file, and is independently tested. Each rule could perhaps define whether it is a blocking rule for purposes of the two-tier validation described above. Somewhere, probably on the model, we provide a list of the rules that apply to it (or maybe this can be done automagically using the type system?). And then the API controllers need to ensure that those checks are run when mutating data, or when the client requests a list of known issues.

**Comment by cmgiven** [comment]
@jlhogan @mmazanec22 @cailyncodes Would love your eyes and ideas here.

**Comment by cailyncodes** [comment]
Question about "I'll be barred from going any further" in bullet point 1: Does this mean barred from saving and moving onto the next child or barred from entering the next section in the enrollment form?

**Comment by cailyncodes** [comment]
Agree with "I think the only place to perform validation is on the server side."

**Comment by cailyncodes** [comment]
For the hard and fast rules, I think we can leverage the GraphQL validation feature. It allows us to validate queries and mutations (the latter is the of value for us in this case) and can block the mutation from running outright -- it is run before any interaction with the db occurs. (This is actually how authorization works [for better or worse]). It allows us to return a list of errors which we can then present to the user. Each of our validations would inherit from `IValidationRule` (see `AuthorizationValidationRule` in our code base as an example) and implement the `Validate` method.

**Comment by cailyncodes** [comment]
For the warning queries, I'm not immediately sure that we can directly use the GraphQL validation as above. I mean, we can apply it to the report mutation, I think, which we could block mutations on report submission and return errors as above. However, I am not sure we could provide warnings on enrollment saving -- we'd have to add data to a successful response (which I don't think is a sustainable approach). My suggestion would be then to have a validation endpoint which we could pretend to run the report submit mutation (which would never actually hit the database) and apply the same validation rules -- displaying the results to the user. It would require two API requests for ever edit, however.

**Comment by cailyncodes** [comment]
As for "This would support adding a new rule that existing data violates. The data was valid at the time it was saved, but now you'll need to correct it before you can submit any reports using it," I'm not sure GraphQL validation gives us this. Because this only operates on the mutation/query level, we'd never be able to inspect the db post facto. Unless we query the db, get the result, and then try to replay a mutation with that exact data? Not sure exactly how the report submit was implemented so I need to take a look at that.

**Comment by cmgiven** [comment]
> "I'll be barred from going any further"

I think that should be immediate. So I couldn't move on to the next section without it.

> GraphQL validation feature

I'll have to check that out. Thanks for the pointer.

> validation endpoint which we could pretend to run the report submit mutation

That feels awkward? I'd like some sort of API where each model has a `validations` attribute (or `warnings`?). Then a single mutation could either return an error (not allowed, failed a hard rule, here's where you went wrong) or a success with the `validations` updated (we saved, but here are some things you might want to inform the user about).

> Because this only operates on the mutation/query level

I'm not sure I follow. I don't think we would be looking to validate the data except during a mutation or a query. The after-the-fact validation would occur when I query for some data submitted long ago, or when I try to submit a report that relies on it.

**Comment by cmgiven** [comment]
Walking skeleton up in #142.

**Comment by jlhogan** [comment]
non-blocking validations: see https://github.com/ctoec/ecis-experimental/pull/406/
blocking validations: leverage dotnet validation stuff, likely using attributes, should be realllllllll easy (potentially biggest challenge: clashing naming tehe)  https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1
