### ISSUE TITLE
Add "back to roster" link to enrollment page

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#145]
As a provider, I want a way to get back to the roster from the enrollment page.  

## Acceptance Criteria
- Adds "Back to Roster" link with icon to enrollment page, left-aligned
- Selecting "Back to Roster" navigates the user back to the roster page 

## Design
[Icon needed]

![image](https://user-images.githubusercontent.com/30734760/67499569-f7613f80-f646-11e9-8ab3-a0f8c06c45d1.png)

**Comment by abbyraskin** [comment]
@atreni could you provide the .svg for the back icon when you have a chance?

**Comment by mmazanec22** [comment]
Arrow SVG is included in USWDS library.

Note from the tech debt doc: "format enrollment detail; add  nav buttons (back to roster? Enroll another child? Confirm in design spec)"

**Comment by mmazanec22** [comment]
Addressed by #340
