### ISSUE TITLE
Project Setup - winged-keys - GitHub, Azure DevOps, SonarCloud

### ISSUE THREAD

**Issue by speedcm** [ctoec/ecis-experimental#148]
Winged keys is being broken out from the hedwig project and will be an atomic component with its own GitHub project, Azure DevOps Services project and SonarCloud project.

Please perform the following to setup winged-keys:
- Setup the winged-keys GitHub project
- Setup the winged-key SonarCloud project
- Setup the winged-keys Azure DevOps project (under the CTOEC organization)
  - Set the project as public so we get the 10 free agents for parallel jobs
- Setup the winged-keys build pipeline (i.e. not release pipeline)
  - This is needed to keep the authentication consistent (user for azure pipeline access = user for github access)

Notes:
- Please do not lock down  GitHub master branch until after CI is setup and we can publish to SonarCloud
  - SonarCloud does not allow the initial (i.e. first time) publish to come from a PR branch

**Comment by cmgiven** [comment]
https://github.com/ctoec/winged-keys

**Comment by cmgiven** [comment]
https://sonarcloud.io/dashboard?id=ctoec_winged-keys

**Comment by cmgiven** [comment]
https://dev.azure.com/ctoec/Winged%20Keys

Can't set up the pipeline until there's code in the repo, by the looks of it.
