### ISSUE TITLE
Add CDC funding section to enrollment

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#150]
**Story**: As a provider, I want to enter a child's funding information so I can enroll them in a program space.

**Acceptance Criteria**:
- Add a header below Age group field that says "Funding" (differs from comp)
- Below, add a "Funding type" dropdown, with the following options (including the standard -select- empty state):
  - CDC - full time
  - CDC - part time
  - Private pay
- If user selects CDC full time or part time as funding type, display the "First reporting period" dropdown, populated with the first reporting period inclusive of the enrollment start date entered, and the next two periods that follow (three total)
- If the user selects "Private pay" as funding type, "First reporting period" is disabled 

**Design**:
![image](https://user-images.githubusercontent.com/30734760/71018903-f7b60e00-20be-11ea-8e4a-0af7f6d2dfe8.png)

**Comment by abbyraskin** [comment]
assigning to myself to get the acceptance criteria once the designs are finalized!

**Comment by abbyraskin** [comment]
@atreni can you add the details for this story please? so far we've only built out the enrollment piece, but we don't have anything for funding yet (you may want to break it into multiple stories to account for the alerts, etc.), thank you!

**Comment by abbyraskin** [comment]
Note: we decided to remove any indication of available spaces from the funding section of enrollment for now until we've had more time to research behavior here!

**Comment by atreni** [comment]
Reporting period dates through end of 2019-2020 fiscal year:
- 10-28-2019 - 11-29-2019 (5 weeks)
- 12-2-2019 - 12-27-2019 (4 weeks)
- 12-30-2019 - 1-31-2020 (5 weeks)
- 2-3-2020 - 2-28-2020 (4 weeks)
- 3-2-2020 - 3-27-2020 (4 weeks)
- 3-30-2020 - 4-24-2020 (4 weeks)
- 4-27-2020 - 5-29-2020 (5 weeks)
- 6-1-2020 - 6-26-2020 (4 weeks)
