### ISSUE TITLE
Discussion: Hedwig validations

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#154]
(e.g., CDC funding month can't be earlier than the enrollment date, age of child, etc.)

- Look at existing validations in ECIS as a starting point? - https://docs.google.com/document/d/1gVnblp25SnmV328vQHTc4k3-fj6Tn8I8FxAEoPAysq4/edit

**Comment by cmgiven** [comment]
I think this would be a good discussion to have in the next week or so?

**Comment by abbyraskin** [comment]
Yes, let's do this next week if possible - who should participate? I would think we need to involve more folks than the design/product team unless you have a handle on it.

**Comment by cmgiven** [comment]
Let's open it up to everyone, and see who's interested in joining?

**Comment by abbyraskin** [comment]
ECIS validation rules: https://docs.google.com/document/d/1gVnblp25SnmV328vQHTc4k3-fj6Tn8I8FxAEoPAysq4/edit

**Comment by abbyraskin** [comment]
- Validate date format
- Validate first reporting period is later than enrollment date
- (Age of child? No greater than 7 years old?
- DOB is later than today
 - Withdrawn date is later than enrollment date
- Withdrawn date is later than beginning of first reporting period
- Formatting for household income

**Comment by abbyraskin** [comment]
@cmgiven can you take a look at this list (will create separate stories for each and we can prioritize appropriately but want to see if you agree w/ these as a starting point? should we cut anything for now?)

**Comment by cmgiven** [comment]
Straightforward.

Validate date format is a different kind of thing, correctly formatting whatever the user types in. It's mostly already handled, but I'd suggest a ticket to support two-digit years would be good.

All of the dollar amount are already done, including household income.

I would suggest rewriting "Withdrawn date is later than beginning of first reporting period" as three rules, "Start of first reporting period is before or the same as the withdrawn date," "Last funding period starts before withdrawn date," and "Last funding period is after or the same as first funding period."

Similarly, "Validate first reporting period is later than enrollment date" would more properly be "End of first reporting period is after or the same as enrollment date." Keep in mind that a reporting period is a range of dates, so it has a start and an end, and we want to compare to one of those dates.

Maybe we should check age with Annette?

**Comment by abbyraskin** [comment]
Thanks! Sure, I took the 7 year thing from ECIS. Let's check. I sort of assume there are exceptions, which makes me a little hesitant on that one as well.
