### ISSUE TITLE
Income information is not required when enrolling a foster child 

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#155]
As a provider, I want to skip the income determination section of enrollment if I am entering a foster child because the child is automatically eligible for state funding.

## Acceptance Criteria
- If a user has selected the "Child lives with foster family" checkbox in the family information section of enrollment (step 2) and selects save, skip the family income section and navigate directly to the enrollment and funding section of the step list (and show step 4 in an edit state)
- On save, step 2 is shown in a complete state (note: this differs slightly from design shown in prototype, avoids adding a third save state)
- Step should should include the following copy:
  - Household income: This information is not required for foster children

### Design
![image](https://user-images.githubusercontent.com/30734760/70919015-ae45c000-1fe5-11ea-9227-5c0859adb8d2.png)
[Invision](https://skylight.invisionapp.com/public/share/QDUDSEK9MP8#/screens/475071032)

**Comment by atreni** [comment]
<img width="581" alt="Screen Shot 2019-12-04 at 11 09 47 AM" src="https://user-images.githubusercontent.com/7797826/70159256-9b96c700-1686-11ea-8837-eb8f6b1f899a.png">

[Invision prototype](https://skylight.invisionapp.com/public/share/W6WXVKAMF)

**Comment by abbyraskin** [comment]
I don't think we need to fill in household size as 1, my understanding is this is a bit of a hack to allow them to receive the largest amount of funding and not something we should or need to continue doing in Hedwig - and it might be confusing since they could live in a larger household?  Also I would recommend a copy change (since the current version implies foster children are entering something) - maybe something like "Income information is not required for foster children"? Also, I don't think we need both an alert saying this information is not required _and_ the "Household income: not required"?
