### ISSUE TITLE
Show success message after enrollment (no missing information)

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#156]
**Story:** As a provider, I want to know if I successfully finished enrolling a child.

**Acceptance Criteria:**
- When a user has completed all required information on the enrollment page and selects `Submit`, they are navigated to the child summary page with a green [success alert](https://design.cms.gov/components/alert/) at the top of the page
- Copy:
  - Header: Enrolled
  - Body: [child's name] has been successfully enrolled in [site name]. 
- When a user has completed all required information on the enrollment page and selects `Submit and enroll another`, they are navigated to an empty enrollment page with the same success alert noted above.

**Design:**
![Child Detail — Summary Success](https://user-images.githubusercontent.com/7797826/70159134-68543800-1686-11ea-94c5-6766b6fcef25.png)

**Comment by abbyraskin** [comment]
Need a story to create alert component

**Comment by atreni** [comment]
![Child Detail — Summary Success](https://user-images.githubusercontent.com/7797826/70159134-68543800-1686-11ea-94c5-6766b6fcef25.png)

**Comment by cailyncodes** [comment]
Makes sense to start after #302 lands

**Comment by mmazanec22** [comment]
Closed by #508
