### ISSUE TITLE
Cancel enrollment

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#158]
**Story:** As a provider, I want to discard an enrollment midway through adding a child.

**Acceptance Criteria:**
- Adds a Cancel button to the enrollment page (bottom, left aligned)
- If a user selects "Cancel" while enrolling a child, display a browser system dialog with the following copy:
  - Header: Cancel enrollment?  
  - Body: If you cancel this enrollment you will lose any data you entered about this child.
  - Buttons: No, Yes
- If a user selects no, close the dialog
- If a user selects yes, delete the record and navigate the user to the roster page

**Design:**
![image](https://user-images.githubusercontent.com/30734760/71135668-e1e04000-21c7-11ea-8c1c-af5ae84265bf.png)

**Comment by abbyraskin** [comment]
Abby to write copy - decided in design sync to use system warning.

**Comment by cailyncodes** [comment]
Thoughts on this: https://alistapart.com/article/neveruseawarning/ @abbyraskin @atreni 

And is "system warning" different from "browser system dialog" different from an alert pop up?
