### ISSUE TITLE
PRs cannot be merged until status checks pass

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#16]
**Story:** As a Skylight developer, I want to ensure that tests are passing on any pull request before I merge it into master.

**Acceptance criteria:**

* Creating or adding a new commit to a PR triggers CI suite to run.
* PRs cannot be merged without automated tests and code linting passing.

**Comment by speedcm** [comment]
By default, "pull request builds are automatically enabled for all branches" in Azure DevOps 2019. Upon looking at the pipeline in Azure DevOps 2019, pull requests are being built. For more information see https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml

**Comment by speedcm** [comment]
This "merged until status checks pass" is working as expected for the Azure DevOps 2019 integration with GitHub.
