### ISSUE TITLE
Child can be created

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#168]
**Story**: As an API consumer, I want to be able to create a new child.

**Acceptance criteria:**
- I should be able to make an authenticated GraphQL mutation like the following:
```
{
createChildWithSiteEnrollment(
  firstName: String!,
  middleName: String,
  lastName: String!,
  suffix: String,
  birthdate: Date,
  birthCertificateId: string,
  birthTown: string,
  birthState: string,
  gender: Gender,
  americanIndianOrAlasskaNative: Bool,
  asian: Bool,
  blackOrAfricanAmerican: Bool,
  nativeHawaiianOrPacificIslander: Bool,
  white: Bool,
  hispanicOrLatinxEthnicity: Bool,
  foster: Bool,
  siteId: Int!
){}
```
IFF my user has access to provided SiteId
- mutation should create a child with all provided fields
- mutation should create an enrollment for the newly created child at the provided site

~**TBD**: for create mutation, should we have the arguments be individual field values (as we do for update muts), or should we create a mut-specific input type that represents a child (as appears to be standard graphql approach https://graphql-dotnet.github.io/docs/getting-started/mutations/)?~
**Decision**: Let's use direct fields instead of defining separate types

**Comment by cailyncodes** [comment]
If we want to support partial saves, I think it makes sense not to create a separate type (even though it breaks standard practice).

**Comment by jlhogan** [comment]
@cailyncodes we can create a separate type, but i'm struggling to figure out what the advantage is. Here, i've updated the inputs to all be optional anyway (except required first name, last name, and siteId). Do you see advantages to creating input types over directly specifying all the fields?

**Comment by cailyncodes** [comment]
@jlhogan @cmgiven An enrollment requires an entry date. Should we:

- Remove that requirement
- Require an API consumer to supply it to this mutation
- Use the current date for the entry date

I would think the final option but wanted to check.

**Comment by cmgiven** [comment]
I think we should remove that requirement.

Looking at the enrollment flow, we can't require it because it won't be supplied until later in the flow.

Generally speaking kids are not being enrolled on the same day they start. Possibly despite that the third option is still reasonable. But it feels a little weird from an API perspective.

(This probably breaks the enrollment query with the date range specified, because that assumes a non-null start.)

**Comment by cailyncodes** [comment]
This makes sense!

And yes, I think it would break the querying (at least under our current domain assumptions about intersection of date ranges). @mmazanec22 maybe has an idea as the person who last updated the query logic?

**Comment by mmazanec22** [comment]
Yes, currently we only handle the case of exit being null
