### ISSUE TITLE
Family determination can be updated

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#176]
**Story**: As an API consumer, I want to be able to update an existing family determination

**Acceptance Criteria**:
- I should be able to make an authenticated GraphQL mutation like the following:
```
{
updateFamilyDetermination(
  id: Int!,
  numberOfPeople: Int,
  income: Number,
  determined: date
) {}
}
```
IFF my user has access to the provided determination id

- the mutation should update the provided determination with any supplied values, and leave other fields as they are

**Comment by cailyncodes** [comment]
Closed by #204
