### ISSUE TITLE
Update Family Model

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#185]
**New Fields**:
- addressLine1: string | null
- addressLine2: string | null
- town: string | null
- state: string | null
- zip: string | null
- homelessness: boolean (false by default)
- determinations: FamilyDeterminations[]

**Comment by cailyncodes** [comment]
> determinations: FamilyDeterminations[] (not a db field)

Currently it is a db field, so should we be removing it?

**Comment by jlhogan** [comment]
> > determinations: FamilyDeterminations[] (not a db field)
> 
> Currently it is a db field, so should we be removing it?

nope. i was wrong! updated

**Comment by jlhogan** [comment]
family <-> familyDetermination relationship in DB is defined on familyDetermination, which has an FK to family (familyDetermination.familyId --> family.Id)

the FamilyDeterminations[] field on Family model is a convenience field

**Comment by jlhogan** [comment]
@cmgiven can you confirm if CaseNumber should be removed from family? Added it to make testing easier, but was not necessarily ever asked for from a design/product perspective. thanks!

**Comment by cmgiven** [comment]
Yes, let's remove. It may come back in the future, but it shouldn't be on family in the short term.
