### ISSUE TITLE
Update Enrollment Model

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#188]
**New Fields**:
- Age: Age | Null

**New Types**:
- Age Enum: [InfantToddler, Preschool, SchoolAge]

**Updated Fields**:
- entry: Datetime | null

**Comment by cailyncodes** [comment]
@cmgiven Oh I'm seeing this enrollment model update here for Entry field.

**Comment by cmgiven** [comment]
Yup! And we should also have Exit in here.

**Comment by cailyncodes** [comment]
Exit is already nullable, but good to explicitly note.

**Comment by cmgiven** [comment]
Ah! I see. This is just the changes. I missed that.
