### ISSUE TITLE
Do functions returning Tasks all need to be defined as `async`?

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#206]

**Comment by cailyncodes** [comment]
TL;DR Nope 😄 

In this helpful article, https://www.hexacta.com/2016/06/01/task-run-vs-async-await/ it outlines that `async` signals to the compiler that the `await` keyword is valid in the enclosed scope and valid return types are `Task<T>`, `Task`, and `void`. An async function is not awaitable, rather the return type (of type `Task | Task<T>` is awaitable. So we can clean up any and all functions returning a Task that does not use `await` to remove async.

**Comment by jlhogan** [comment]
> So we can clean up any and all functions returning a Task that does not use `await` to remove async.

except controller actions, which need to have the resolved entity to infer the return type

**Comment by cailyncodes** [comment]
I think I follow but can you clarify controller actions? I think we use `await` in all controller methods.

**Comment by jlhogan** [comment]
yes we do sorry. i was just saying we need to :)

**Comment by cailyncodes** [comment]
Closed by #612
