### ISSUE TITLE
Where should Schema namespace live?

### ISSUE THREAD

**Issue by cailyncodes** [ctoec/ecis-experimental#207]
If we're going to add a GraphQL namespace to our project, should `Schema` live inside it? Not blocking for this PR (in fact, we need to move on this so def don't impl in this PR) but wanted to flag

_Originally posted by @jlhogan in https://github.com/ctoec/ecis-experimental/pull/195_

**Comment by cailyncodes** [comment]
I would support adding Schema as a subnamespace to GraphQL. I'm also open to not having a GraphQL namespace; I just don't know where to put the files in that namespace -- def open to suggestions.

The reason this namespace renaming is required is due to Hedwig.GraphQL and GraphQL conflicting when resolving the namespace later in this file.

**Comment by jlhogan** [comment]
wont fix -- graphQL bye bye
