### ISSUE TITLE
Naming of alternative gender enum value

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#216]
Gender enum: [Male, Female, Unspecified, *]

- research and make recommendation to OEC
- gather requirements around alignment with SDE naming, and any associated laws

**Comment by cailyncodes** [comment]
A website I created about gender options on forms: [http://whatsyourgender.com/](http://whatsyourgender.com/). It has some arguments and 3rd party sources.

**Comment by cailyncodes** [comment]
I threw together a document that provides some initial outlines/thoughts/questions for framing and potential next steps: https://docs.google.com/document/d/1Vv1KJ7eKz9yPP8mbrPrSFo8mXhTP1g9qnaPMoPvd9vw/edit

**Comment by abbyraskin** [comment]
I did a bit of digging and found out PSIS (CT public schools database) has a third option (non-binary) - this was added for the 2017-2018 school year, so I think we have a good case for minimally including this option in our list (assuming a fixed set of options is preferred or required).

Questions for Julie/OEC (reworded a bit for my own brain in advance of talking to julie, but mostly stolen from Cailyn!):
- Why is gender collected in ECIS?
- How should providers determine gender? "As identified by family"? (similar to race/ethnicity collection?) - we could include helper text in the application 
- Do we need a fixed set of options?
- PSIS requires users to choose from one of three options: male, female, non-binary (updated in 2017 to add third option) - this could be a good starting point for a more inclusive collection?  How important is to match SDE's collection? 
- Currently, ECIS includes an "unknown" option. Where did "unknown" come from? In the new system, if we do provide a fixed set of options, should we include an explicit "unknown" (e.g., "family did not identify") option?

**Comment by abbyraskin** [comment]
To close the loop on this discussion for now, I suggest for Hedwig we recommend adding a fourth "non-binary" option and keep the other user-facing options as-is (male, female, non-binary, unknown) - I will include this in the data collection doc (and we can continue researching other ways to improve on this and other collections in a future iteration?). I can make the dev ticket once the short-term change is approved.
