### ISSUE TITLE
Determine colors for roster tags (current ones fail https://webaim.org/resources/contrastchecker and Abby doesn't like them)

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#224]
Currently our roster tag colors are failing so we need to update the colors.

**Acceptance Criteria:**
Update roster tags to include the following colors:
- CDC tag: USDS bg-blue-50v: hex # 0076D6
- C4K tag: USDS bg-violet-warm-60: hex # 864381
- Missing information tag: [Needs updating]
- Success color: USDS bg-success: hex # 0CA900

**Design:**
<img width="729" alt="Screen Shot 2019-12-04 at 11 01 51 AM" src="https://user-images.githubusercontent.com/7797826/70158606-85d4d200-1685-11ea-9dd2-0eeac3ecbb84.png">

**Comment by atreni** [comment]
<img width="729" alt="Screen Shot 2019-12-04 at 11 01 51 AM" src="https://user-images.githubusercontent.com/7797826/70158606-85d4d200-1685-11ea-9dd2-0eeac3ecbb84.png">

- CDC tag: USDS bg-blue-50v: hex # 0076D6
- C4K tag: USDS bg-violet-warm-60: hex # 864381
- Missing information tag: USDS bg-gold-30v: hex # E5A000
- Success color: USDS bg-success: hex # 0CA900

**Comment by abbyraskin** [comment]
To do: update the missing information color so it isn't failing and pick colors that pass for additional funding streams for future.
