### ISSUE TITLE
API v2 Spec

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#230]
`/users` (GET/POST)
|---`/:id` (GET/PUT)
|---`/current` ?
`/organizations` 
|---`/:id` 
|---|---`/sites`
|---|---|---`/:id` 
|---|---|---|---`/enrollments` (GET/POST)
|---|---|---|---|---`/:id` (GET/PUT)
|---|---`/children` (GET)
|---|---|----`/:id` (GET/PUT)
|---|---`/families` (GET)
|---|---|---`/:id` (GET/PUT)
|---|---`/reports` (GET/POST)
|---|---|---`/:id` (GET/PUT)

For Pilot MVP:
- users will only create families & children via `.../enrollments`
- children and families will be updated via PUT to `.../enrollments/id`

**Comment by cmgiven** [comment]
We don't have to worry about org-level access to children until we get to supporting multiple sites, but I suspect that it would be useful at that point.

Thoughts on advantages of nesting everything under organization versus a flatter schema? As a strawman, something like:

`GET /users/:id` (Name and lists of the organizations and sites I have access to.)
`GET /sites/:id/roster`, `GET /organizations/:id/roster` (Roster of a site or organization; potentially would need additional parameters to filter by date.)
`POST /children` (Create a new child.)
`GET /children/:id` (Everything about a child, including enrollments, fundings, etc.)
`PUT /children/:id` (Update a child.)
`POST /families`
`GET /families/:id`
`PUT /families/:id`
`GET /reports` (List of all reports I have access to.)
`GET /reports/:id`
`GET /reports/:id/roster` (Roster as of the time the report was submitted.)
`POST /reports/:id/submit`
`POST /reports/:id/revise`

And then, only models that can only ever be accessed through a single parent are nested.

`POST /families/:id/determinations` (Create a new determination.)
`GET /families/:id/determinations/:id`
`PUT /families/:id/determinations/:id`
`POST /children/:id/enrollments`
`GET /children/:id/enrollments/:id`
`PUT /children/:id/enrollments/:id`
`POST /children/:id/enrollments/:id/fundings/`
`GET /children/:id/enrollments/:id/fundings/:id`
`PUT /children/:id/enrollments/:id/fundings/:id`

I know that a child can only ever have one organization in our model. But as a child could be enrolled in multiple sites, or a family could have multiple children, maybe that's a reason to avoid nesting those models?

**Comment by cailyncodes** [comment]
Addressing the ?s in the initial comment.

* I support `/user/current` for the authenticated user. But we could also use `/user/me` to have a parallel to GraphQL, I suppose.
* I like `/.../children?includeFamily=true` as opposed to always serving up family in the response. (This is perhaps veering away from idiomatic patterns but I like it better than needing to make a separate network request or overfetching.)
* Re permissioning: I feel like we do what you have written above or we have to include `organizationId` and `siteId` on everything object we create in the db. And I thought that was decided that we weren't going to do that?

**Comment by jlhogan** [comment]
Should we implement an `include` query param that enables any nested sub-object, or nest-able parent object to be returned with a given fetch? 
.../children; include=[family,enrollments]
.../families; include=[children,determinations]
.../enrollments; include=[fundings]

**Comment by cmgiven** [comment]
I wonder whether that's adding complexity for not much gain? I think we'd pretty often need to go two levels down (e.g. child -> family -> determinations). It might be better just to be more opinionated and include the nested objects we would expect to need, so a child will always give me the family and determinations, as well as the enrollments and fundings. It's not a ton of data.

**Comment by jlhogan** [comment]
makes sense to me.
SO...

models:
`child` always includes `family`
`family` always includes `determinations`
`enrollment` always includes `fundings`

endpoints: stay the same, altho `GET`s at `.../families`, `.../determinations` and `.../fundings` are likely not going to be used much. However, these endpoints will still be used for `POST`s and `PUT`s

**Comment by cmgiven** [comment]
`enrollment` also needs to include some information about the `child`. We know it needs the name fields and the birthdate.

Yeah, that seems right. And even if we rarely `GET` a family, we'd perhaps use the same response for a successful `POST` or `PUT` as we would for the `GET`.

**Comment by jlhogan** [comment]
1) do we want to embed subset objects, i.e. only a few fields on child returned on the `enrollments` object? or just throw the whole object in? 
2) do we want to include the `*Id` field on objects that are actually nested eg should an `enrollment` contain a `childId` and ` child` object without, or just a `child` object that includes an `id` field? If leaving the childId is easier (i imagine it is) do we really care?

**Comment by cmgiven** [comment]
I don't have strong feelings on 1. It does feel like the kitchen sink if when I request the enrollments for a site, I get everything that's descended from child when I really only need id, name, and DOB. So maybe subset?

On 2, I don't see a reason that would be needed from the client side. But there's absolutely no harm in leaving it in if that's easier.

**Comment by jlhogan** [comment]
spec for pilot MVP complete
