### ISSUE TITLE
Add "Back to reports" link to CDC report

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#272]
**Story:** As a provider, I want a way to return to the reports list so I can reference a different report.

**Acceptance Criteria:**
- Adds a "Back to reports" link to the CDC report page (same icon used in enrollment)
- Clicking this link navigates the user to the reports list 

**Design:**
![image](https://user-images.githubusercontent.com/30734760/68957053-dcd63e00-078e-11ea-83bd-3cb30220ffa4.png)

[Invision prototype](https://skylight.invisionapp.com/share/QDUDSEK9MP8#/screens/390268232)

**Comment by mmazanec22** [comment]
Grabbing this and the other back link ticket; making one component with rotate-able arrow

**Comment by mmazanec22** [comment]
Addressed in #340
