### ISSUE TITLE
Draft indicator on pending reports 

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#276]
**Story:** As a provider, I want to be able to distinguish between a report that is in progress and one that has already been submitted.

**Acceptance Criteria:**
* If the report has not been submitted, a tag with the text "DRAFT" should appear at top of the report page.

![68957053-dcd63e00-078e-11ea-83bd-3cb30220ffa4](https://user-images.githubusercontent.com/5375557/70054076-6a41cc80-159c-11ea-8b2e-da83226ce9d5.png)

**Comment by mmazanec22** [comment]
Addressed by #347
