### ISSUE TITLE
Requirements for pilot authentication

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#281]
- [ ] UI Requirements ?
- [x] password reset ?
- [x] client token persistence ?

**Comment by jlhogan** [comment]
no password reset

**Comment by jlhogan** [comment]
yes client token persistence

**Comment by jlhogan** [comment]
UI - what's doable in half day (e.g. make purple, add icon, add "OEC")

**Comment by cailyncodes** [comment]
> UI - what's doable in half day (e.g. make purple, add icon, add "OEC")

The built-in code is all server-side templating with direct CSS. I think it would be viable to remove "Identity Server" branding, add some OEC text, and non-complex styling (possibly being able to add some UWDS post-compiled CSS? -- much larger LOE)

**Comment by cailyncodes** [comment]
Just remembered we also have ctoec/winged-keys#2

**Comment by cailyncodes** [comment]
@victoriasuwardiman @atreni 
Do we want to make styling edits, and if so, any must-haves?

**Comment by victoriasuwardiman** [comment]
Is this the "login" and "permissions" pages? Looking at the comments above, what's doable?

**Comment by cailyncodes** [comment]
Yes -- And rudimentary styling and layout changes are possible. Probably no fun interactive elements.

**Comment by cailyncodes** [comment]
Closing this as the pilot is beginning tomorrow and there appears no need for auth changes before that point
