### ISSUE TITLE
user account creation plan

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#282]
For post-pilot, we will need to implement:
- creation of user accounts  in winged-keys
- creation of users in hedwig when a new winged-keys user appears 
- method for configuring user permissions 

For pilot, it will be much simpler to pre-create winged-keys user accounts and hedwig users and permissions. However, if we do this we will be pre-defining providers' passwords, which may not feel great. Could force a requirement of supporting password reset, so the pilot participants are able to create new passwords

**AC**:
- [ ] what is acceptable for providers?
- [ ] does that change auth mvp requirements ?
- [ ] create user accounts, users, and permissions for pilot participants

**Comment by cailyncodes** [comment]
> create user accounts, users, and permissions for pilot participants

Blocked by production database for WingedKeys > Blocked by AWS Setup

**Comment by cailyncodes** [comment]
For pilot, complete, closing.

For post-pilot, we have #107
