### ISSUE TITLE
Providers can print the CDC report

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#283]
**Story:** As a provider, I want to print my CDC report for my records.

**Acceptance Criteria:**
- Selecting "print" on the CDC report detail page launches a standard print styling/window (reuses what we already built)

**Design:**
![image](https://user-images.githubusercontent.com/30734760/69661629-594b0580-1048-11ea-9325-745f1be5cb92.png)
[Invision prototype](https://skylight.invisionapp.com/public/share/QDUDSEK9MP8#/screens/390268234)

**Comment by cailyncodes** [comment]
![Report Print Screenshot](https://user-images.githubusercontent.com/16420449/70934371-c3cde080-200b-11ea-914e-9880415cf07c.png)

Screenshot of print page
