### ISSUE TITLE
hedwig - docker-compose up - container only works on developer desktop

### ISSUE THREAD

**Issue by speedcm** [ctoec/ecis-experimental#285]
The docker image created with docker-compose up can only run on a developer desktop (e.g. redirects to localhost).  The docker image needs to be able to run on any AWS EC2 system.

**Comment by cailyncodes** [comment]
@speedcm Follow up from our call. The following app settings variables in WingedKeys need to be changed at release time:
* `RedirectURIs` --> `https://[IP/Hostname of EC2 instance of Hedwig]:[Port number]/login/callback`
* `PostLogoutRedirectURIs` --> `https://[IP/Hostname of EC2 instance of Hedwig]:[Port number]/`
* `AllowedCorsOrigins` --> `https://[IP/Hostname of EC2 instance of Hedwig]:[Port number]`

Outstanding question: How to set a runtime React environment variable for specifying the URL of WingedKeys?

**Comment by cailyncodes** [comment]
We'll also need to set:
* `PublicOrigin` --> `https://[IP/Hostname of the EC2 instance of Hedwig]:[Port number]`

This config exists after ctoec/winged-keys#16 lands.

**Comment by speedcm** [comment]
Can we please setup the appsettings.json file with these default entries? Azure devops pipeline can only replace entries in json file if it exists. Should we put the values in alphabetical order (not sure if this is normal)?

 It would be great if the parameters where evaled or derived (e.g.e only specify the host names in the appsettings file) to simplify the file.

**Comment by speedcm** [comment]
This issue is resolved.  The application source code & settings were modified to allow for building the docker containers on a non-developer system.  Currently, the code supports building a docker container on an EC2 system during a PR.
