### ISSUE TITLE
hedwig - release - dotnet publish - only works on developer desktop

### ISSUE THREAD

**Issue by speedcm** [ctoec/ecis-experimental#287]
The hedwig release created by dotnet publish can only run on a developer desktop. The release must be able to run on a AWS Beanstalk system.

**Comment by cailyncodes** [comment]
In addition to the config parameters in #285, we'll also need to set:

* `PublicOrigin` --> `https://[IP/Hostname of the EC2 instance of Hedwig]:[Port number]`

This config exists after ctoec/winged-keys#16 lands.

**Comment by speedcm** [comment]
This issue is resolved.  The hedwig source code now builds in Azure pipelines and deploys to AWS Beanstalk systems.
