### ISSUE TITLE
Roster can be printed

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#3]
**Story:** As a provider, I want to print out my roster for my records.

**Acceptance criteria:**

* My roster has a button below the table of enrollments labeled "Print".
* This button uses the "outline" style from USWDS.
* Clicking this button opens the browser print dialog.
* A print stylesheet changes the page:
  * The header is hidden.
  * Buttons like the "Print" button are hidden.
  * Links are ink-colored and not underlined.
  * The content fits to the width of a portrait 8.5x11" page.

**Design:**

<img width="548" alt="Screen Shot 2019-09-15 at 9 15 24 AM" src="https://user-images.githubusercontent.com/5375557/64924376-a473ad00-d7a9-11e9-93f4-7ceda2b3fe35.png">

<img width="1054" alt="Screen Shot 2019-09-15 at 9 27 22 AM" src="https://user-images.githubusercontent.com/5375557/64924377-a6d60700-d7a9-11e9-875c-e861ce780f46.png">

**Comment by cailyncodes** [comment]
I think there needs to be another point on the AC. I see two options:
* The ability to hit the browser's back button to return to the non-print version
* The ability to close the print version to return to the non-print version

I'm going to operate pursuant to the second of the options but feel free to flag otherwise.

**Comment by cmgiven** [comment]
Yup! Yeah, I originally wrote a spec about opening a new window with the print version. And then I remembered that print stylesheets are a thing.

**Comment by cailyncodes** [comment]
Are funding tags included in the print out?

**Comment by cmgiven** [comment]
Yup! The logic is that we're only showing the page content, and hiding anything related to interaction. So the header is hidden. Buttons are hidden. Links are shown as plain text instead of blue underlines. But something that communicates information, like the funding tags, should remain.

**Comment by cailyncodes** [comment]
Sounds good! I went ahead with that approach but I just wanted to make sure

**Comment by cailyncodes** [comment]
Resolved by #39
