### ISSUE TITLE
Success alert after saving enrollment with missing information

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#302]
**Story:** As a provider I want to know that I still need to complete missing information for a CDC-funded child I just enrolled in my program.

**Acceptance Criteria:**
- After saving a new enrollment for a child assigned to a funded space,  display a success alert - this copy is specific to the scenario where a child was successfully enrolled but is still missing information required for the report 
- This alert is displayed on the child summary page if the user selected "Submit" during enrollment, or on the (blank) enrollment page if the user selected "Submit and enroll another" 
- Copy
  - Header:  Enrolled
  - Body: [Child's name] has been enrolled in [site name]. However, there is missing information you are required to enter before you can submit your monthly CDC report. 

**Design:**
<img width="677" alt="Screen Shot 2019-12-16 at 8 45 24 AM" src="https://user-images.githubusercontent.com/7797826/70911719-7720e000-1fe0-11ea-9fae-ec8366af7c6f.png">

[Invision prototype](https://skylight.invisionapp.com/public/share/4BX1FH58F)

**Comment by abbyraskin** [comment]
Discussed making this green instead - @atreni can you update this ticket please?

**Comment by atreni** [comment]
<img width="594" alt="Screen Shot 2019-12-13 at 2 24 56 PM" src="https://user-images.githubusercontent.com/7797826/70826216-5b38f680-1db4-11ea-90f7-24ea575d4646.png">

**Comment by atreni** [comment]
Updated comp for: successful enrollment, missing information

<img width="677" alt="Screen Shot 2019-12-16 at 8 45 24 AM" src="https://user-images.githubusercontent.com/7797826/70911719-7720e000-1fe0-11ea-9fae-ec8366af7c6f.png">
