### ISSUE TITLE
Add "Family income not disclosed" checkbox to funding step of enrollment

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#303]
**Story:** As a provider, I want to enter private pay children who I may not have reported income information.

**Acceptance Criteria:**
- Adds a checkbox to the family income determination step of enrollment, with the label "Family income not disclosed"
- If this checkbox is selected, collapse the additional fields in this section and display a headerless information alert, with the following copy:
  - Income information is required to enroll a child in a CDC funded space. You will not be able to assign this child to a funding space without this information.
- If the checkbox is not selected (or de-selected), return to the previous state (with all fields showing)
- If the user selects "save" and the "income not disclosed" checkbox is selected, display an alert on the next step (step 4, see design below), with the following copy:
  - Funding options not available because family income was not provided. To change, edit the previous section.

**Design:**
![image](https://user-images.githubusercontent.com/30734760/71010048-e108ba80-20b0-11ea-9db4-9872122217bb.png)

![image](https://user-images.githubusercontent.com/30734760/69984466-cc4bf480-14fe-11ea-876e-5dbc86953a86.png)

**Comment by jlhogan** [comment]
should the user be required to either enter  determination OR select checkbox? Or, is hitting save with empty fields and un-checked box allowed?

**Comment by abbyraskin** [comment]
I would think they need to do one or the other or it becomes "missing information" (they shouldn't be completely blocked from saving, but it would block them from submitting the report).

**Comment by jlhogan** [comment]
@cmgiven to impl this, we need to persist the state of the not disclosed checkbox. Easiest way to do this would be to add it to a model. Would it make sense to put a boolean on the enrollment?

**Comment by cmgiven** [comment]
I would think on the `FamilyIncome`? But yes.

**Comment by jlhogan** [comment]
confused sorry -- `FamilyIncome` is not a backend model. 

it sounds like we want to differentiate between deliberately not providing income VS haven't provided any income determination info for the purposes of alerting on missing information.

seems that to do this most easily, a separate boolean to indicate if the user has deliberately not provided income info is helpful.

maintaining state of that separate boolean  (between diff sections, or when going back in to edit the section) is simplest if it just lives on the enrollment or a sub-object somewhere. to my mind, `enrollment` or `family` are the options that make sense, but it seems more like the lack of determination info is enrollment specific, as opposed to applying to the generalized family?

**Comment by cmgiven** [comment]
Sorry, meant `FamilyDetermination`. All that makes sense. I'm thinking of it as a kind of income determination, in this case, that they decided not to do one. Issue with `enrollment` is that we expect a child to have multiple enrollments, and I think we'd expect the flag to stay with the child. `family`'s a possibility, though.

**Comment by jlhogan** [comment]
ah that makes sense! will go forward with "treat not provided as new determination type"

**Comment by abbyraskin** [comment]
Could we make both of these alerts the small alert style (no header)? (We decided to remove the header from the first one after the AC were written - if it's too late we we can make the change later, no worries).

For some reason the styling of the (smaller) alert seems off - maybe there is extra spacing on the top/bottom? It feels large. This is probably not worth being nit picky about at this stage, just wonder if we're using the right component. (Alert component without a heading).

And then really getting picky here, add a period to the end of the second alert please.

**Comment by abbyraskin** [comment]
@jlhogan this is now up to date.
