### ISSUE TITLE
Update roster legend UI

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#307]
**Story:** As a provider, I want to understand what information is shown on my roster.

**Acceptance Criteria:**
- Update existing roster legend with the following (see design):
  - Count of CDC spaces filled
  - Count of children receiving Care 4 Kids
  - Missing information alert
- Note: remove border from legend shown in design

**Design:**
![image](https://user-images.githubusercontent.com/30734760/70179689-17ebd300-16a4-11ea-9bc0-8591ee6177ff.png)

[Invision prototype](https://skylight.invisionapp.com/public/share/QDUDSEK9MP8#/screens)

**Comment by mmazanec22** [comment]
Planning to combine this with https://github.com/ctoec/ecis-experimental/issues/304

**Comment by jlhogan** [comment]
@mmazanec22 i completed some of this in PR #369 but the styling is bad

**Comment by mmazanec22** [comment]
Ok-- @jlhogan everything except the total number of spaces available is done in this one, and I also ditched the redundant SVGs: https://github.com/ctoec/ecis-experimental/tree/307-legend-ui-update
