### ISSUE TITLE
Show missing information indicators on roster

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#308]
**Story:** As a provider, I want to know if a child's information still needs to be entered prior to submitting the monthly report.

**Acceptance Criteria:**
- If a child on the roster is missing "required" information, show a visual indicator next to that child's name 
on the roster

**Design:**
![image](https://user-images.githubusercontent.com/30734760/70185290-17a50500-16af-11ea-88b1-232bae0b0203.png)

**Comment by abbyraskin** [comment]
I think we should sync on whether to include the redetermination reminders for MVP - I would recommend we hold off, so I've limited the AC to the missing child information for now.

**Comment by atreni** [comment]
Updated comp for "missing information" indicator on Summary page. Keep consistent with placement during enrollment flow (above "edit" link):
<img width="741" alt="Screen Shot 2019-12-10 at 2 10 29 PM" src="https://user-images.githubusercontent.com/7797826/70560698-12d0cd00-1b57-11ea-85ad-f4408481f063.png">

**Comment by abbyraskin** [comment]
Note: this may change slightly based on conversation with Ashley today so moving this back to the backlog until this is finalized

**Comment by jlhogan** [comment]
FYI showing missing information alerts in roster is implemented in an open PR. However, missing information alerts on detail and summary views of enrollment are not. Maybe useful to update this ticket to reflect that.

**Comment by abbyraskin** [comment]
(#461 covers the summary page and #157 covers enrollment saved states - closing this one out since it's now moot seeing your comment above!)
