### ISSUE TITLE
Support non-US birth certificates during enrollment

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#314]
**Story:** As a provider, I want to enroll kids who were not born in the US.

**Acceptance Criteria:**
- (TBD - updated design for clearer non-US entry)

**Design:**

**Comment by abbyraskin** [comment]
We should first figure out if we need this for pilot - are there any non-US born children in any of our pilot sites?

**Comment by abbyraskin** [comment]
We might want to incorporate a "no ID" option for non-CT certificates? Also may need to adapt rules for SR funding (if certificates are not required).

**Comment by julyytran** [comment]
Moved to design board and combined #432 for further research/design
