### ISSUE TITLE
Source should be required on funding-- should not default to gray for tags in roster table

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#327]

**Comment by cailyncodes** [comment]
Not quite sure what this is flagging, but I made a fix in a previous PR to update the roster table tag when funding is not selected. Did that resolve this?

**Comment by mmazanec22** [comment]
I think this is left over from right after the graphql/rest switch out when we were having weirdness with required things being able to be null, and we were doing some front end gymnastics to accommodate that.  If there are no issues or they have been addressed I vote we close it.
