### ISSUE TITLE
OmniSharp fails to load packages in docker

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#33]
**Description:**

When opening the docker-ized project in Visual Studio Code on Mac, the project fails to load with the following error:

```
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "ResolvePackageAssets" task failed unexpectedly.
```

Julia was able to reproduce.

**Expected behavior:**

The project opens without any errors, and type checking and other OmniSharp features work in Visual Studio Code.

**Comment by jlhogan** [comment]
VSCode extension for developing inside containers enables running VSCode from within a dotnet container: https://code.visualstudio.com/docs/remote/containers

I have added configuration for this extension (https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) to the project in `/.devcontainer`. An additional docker-compose file overrides the "command" to ensure shutting down VSCode does not stop the container process. A `devcontainer.json` file configures the extension, specifying extensions to install in the container, and what path to use.

With this set up in VSCode, I was able to "attach to existing container", to launch VS code from the docker-compose project running the dotnet app.

If you are still having issues, please let me know!

**Comment by jlhogan** [comment]
^ Additional caveat for above setup. In order for this to work properly (i.e. not shut down your docker-compose containers when you close VSCode) you must chose the extension option to attach to a running container. It will give you the option of all of the services running in your docker-compose project; choose "backend". Following the prompts, open the "/app" folder. From there you should be set.
