### ISSUE TITLE
DevOps - GitHub Repisitory

### ISSUE THREAD

**Issue by speedcm** [ctoec/ecis-experimental#334]
As a member of the DevOps team, I need a version-controlled repository to store my scripts.  

Please create a GitHub repository for the DevOps team.  Please allow access for the Hedwig team members (there are 2 DevOps persons).  This project will not be analyzed by Sonar.  This project will not be processed by Azure DevOps.

**Comment by cmgiven** [comment]
Should we use this one? Needs to be under the skylight organization in order to remain private. https://github.com/skylight-hq/ctoec-devops

**Comment by speedcm** [comment]
The repo should be private and we can use that repo.  Can you please make sure that both DevOps team members have access?

**Comment by cmgiven** [comment]
Yup!
