### ISSUE TITLE
Navigate to reports list after submitting report and display success alert

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#335]
**Story:** As a provider, I want to know that I submitted my monthly report successfully.

**Acceptance Criteria:** 
- After selecting the "Submit report" button on the report page, if the report is submitted successfully, navigate user to reports list page
- Submitted report is no longer in "pending" state and is shown under "Submitted reports"
- (Display a standard green success alert on the reports list page - https://github.com/ctoec/ecis-experimental/issues/167)

**Design:**
![image](https://user-images.githubusercontent.com/30734760/70075293-1b0e9280-15c2-11ea-8107-d34e78f17013.png)

[Invision prototype](https://skylight.invisionapp.com/public/share/QDUDSEK9MP8#/screens/475069162)

**Comment by abbyraskin** [comment]
Do we need a fail state on this one?

**Comment by abbyraskin** [comment]
Do we even need this story still?

**Comment by cmgiven** [comment]
Yeah, checking in on this. We currently take you to the submitted report. The alert shows there. Do we want to go back to the full list, or show you what you just submitted?

**Comment by abbyraskin** [comment]
I think full list makes sense (as shown in the prototype) - @atreni do you agree?

**Comment by atreni** [comment]
Yes very much agree! Would like to have the success alert on the summary page (as shown in the prototype!).
