### ISSUE TITLE
Show count of pending reports in subnav

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#337]
**Story:** As a provider, I want a visual cue that my report is ready for review.

**Acceptance Criteria:**
- Add a number count to the reports sub-navigation, designating the number of pending reports in the queue (see design)
- If there are no pending reports in the queue, do not show any parentheses or number

**Design:**
![Roster V5](https://user-images.githubusercontent.com/7797826/70157414-8d937700-1683-11ea-9f0f-fc2468acb242.png)

**Comment by atreni** [comment]
Updated designs with final indicator. This has changed from a color to the # of pending reports in the table.
![Roster V5](https://user-images.githubusercontent.com/7797826/70157414-8d937700-1683-11ea-9f0f-fc2468acb242.png)

**Comment by abbyraskin** [comment]
looks great, updated the AC

**Comment by cmgiven** [comment]
Closed by #385.
