### ISSUE TITLE
Update designs based on MVP req + product discussions

### ISSUE THREAD

**Issue by atreni** [ctoec/ecis-experimental#342]
Weekly product syncs have helped hone in what is critical for MVP. Designs and prototype are being updated to reflect these decisions [(notes tracked here](https://docs.google.com/document/d/17aFYIxYI8fOwfvnyQY-ll7DiadM69nZ4p_scWMN2ad0/edit)).

**Comment by cmgiven** [comment]
@atreni This issue should be closed, yeah?
