### ISSUE TITLE
Generate draft reports automatically 

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#363]
**Story:** As a provider, I want to see when a new report draft has been generated so I can start entering any missing information.

**Acceptance Criteria:**
- On the `PeriodEnd` date of a CDC `ReportingPeriod` (always a Sunday), a new `Report` should be created for each `Organization` that has at least one CDC `FundingSpace`.
- `ReportingPeriodId` should be the period that has just ended.
- `Accredited` should be equal to `Accredited` from the last report submitted by the organization (the most recent report by `ReportingPeriod` that has a `SubmittedAt` date).
- All other values should be their defaults or null.

**Comment by cailyncodes** [comment]
Possibly helpful: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio and https://thinkrethink.net/2018/05/31/run-scheduled-background-tasks-in-asp-net-core/

**Comment by abbyraskin** [comment]
@cmgiven can you help flesh out the AC here on the tech side since you created these before? e.g., what's the logic for determining which reports to create and what constitutes a pending report (what are the values for the fields in the CDC report table)

**Comment by cmgiven** [comment]
Updated.
