### ISSUE TITLE
Monthly project demos (Wednesday 12/11)

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#373]
_Teams each give a 10 minute overview of what they've done and what they're planning on doing - light weight, slides optional, can be a live demo, can even be a review of documentation that already exists_

What do we want to demo? Who wants to speak?

Some suggestions:
- Update on pilot timing, quick information about our participants (characteristics about the sites)
- User research happenings
- Show what we've built so far using our staging environment (and the fact that we have a staging env!)
- Other stuff in flight/moving pieces
 - What we're still working on or other moving pieces in flight? 
   - Inviting pilot participants
   - Additional features (InVision)
   - Penetration testing
- Lessons/challenges:
  - Getting starter data
  - Getting approval, aligning on scope (e.g., wanting to do everything at once)
  - Who and how to involve people (perception of excluding people from process - relates to above)

**Comment by abbyraskin** [comment]
- Victoria to demo!

**Comment by cailyncodes** [comment]
Wonderful job by Victoria!!
