### ISSUE TITLE
TBD: Withdraw child info page

### ISSUE THREAD

**Issue by atreni** [ctoec/ecis-experimental#391]
**Story:** As a provider, I want to remove a child from my roster to assign a new child to a funding space.

- Add "withdraw" CTA to child summary page
- Withdraw child info page shares contact info for Team Skylight with instructions on how to request withdraw (email a request with URL from child summary page (copied onto the page))
- Include instructions in onboarding guide

<img width="741" alt="Screen Shot 2019-12-10 at 2 10 29 PM" src="https://user-images.githubusercontent.com/7797826/70560789-385dd680-1b57-11ea-8037-2a5c72b3a9de.png">

[Invision prototype](https://skylight.invisionapp.com/public/share/GXX1CXOEW)

**Comment by cailyncodes** [comment]
Pretty sure this can be closed. (Sorry if my closing it is premature)
