### ISSUE TITLE
align `enroll child` CTA with program title

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#392]
![](https://user-images.githubusercontent.com/30734760/70179689-17ebd300-16a4-11ea-9bc0-8591ee6177ff.png)

**Comment by cmgiven** [comment]
<img width="755" alt="Screen Shot 2019-12-11 at 12 20 52 PM" src="https://user-images.githubusercontent.com/5375557/70648460-b16d3480-1c10-11ea-9482-9a7c014fe533.png">

Screenshot is not quite right either. This is what we're looking for: the baselines should align.
