### ISSUE TITLE
aligment/spacing tweaks on roster

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#394]
- tables are misaligned (see screenshot below)
- add space between child name and ! icon
- missing information text and icon slightly misaligned in legend 

![](https://user-images.githubusercontent.com/7797826/70562404-55e06f80-1b5a-11ea-9509-2dcaab687a84.png)

**Comment by cmgiven** [comment]
Also, please add margin below each table so there's space between them and the next table's header. Probably about 48px (USWDS unit: `6`).
