### ISSUE TITLE
update link styling

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#395]
current styling:
![Capture d’écran 2019-12-11 à 9 20 53 AM](https://user-images.githubusercontent.com/54035880/70629132-7579a580-1bf7-11ea-8d87-509d73c89ac6.png)
desired styling:
![Capture d’écran 2019-12-11 à 9 24 16 AM](https://user-images.githubusercontent.com/54035880/70629386-e8831c00-1bf7-11ea-8281-8a5788191548.png)

links exist in:
- child detail view (back to roster)
- report detail view (back to reports)

**Comment by atreni** [comment]
Just double checking that the text is bold. It appears to be regular font weight! @cailyncodes 
<img width="215" alt="Screen Shot 2019-12-13 at 1 58 41 PM" src="https://user-images.githubusercontent.com/7797826/70824674-b23ccc80-1db0-11ea-99be-970cd2ccdf70.png">
