### ISSUE TITLE
Styling for missing information

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#397]
- move `missing information` or `complete` indicator above `Edit` link in enrollment section summary views

![](https://user-images.githubusercontent.com/7797826/70562182-e9657080-1b59-11ea-97e9-dd4f4311ef52.png)

**Comment by atreni** [comment]
@jlhogan update for this ticket re: bullet point 2 regarding alert text. Remove the alert entirely (when a provider clicks on a child name from the roster). The alert will only appear upon completion of the enrollment flow.
