### ISSUE TITLE
Remove "Update" and "Reset" buttons

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#403]
<img width="278" alt="Screen Shot 2019-12-11 at 12 10 47 PM" src="https://user-images.githubusercontent.com/5375557/70647763-51c25980-1c0f-11ea-985a-39be6c4fe6c1.png">

These buttons are a holdover from before we had a DatePicker component. It doesn't make sense to have a second click (and "Reset" is just confusing).

**AC:**
* The buttons are removed.
* The roster updates immediately after the date picker is changed.
* "Show current enrollments" continues to work as expected.

**Comment by cailyncodes** [comment]
Closed by #438
