### ISSUE TITLE
Tabular numerals appear in a different font

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#405]
<img width="989" alt="Screen Shot 2019-12-11 at 3 29 41 PM" src="https://user-images.githubusercontent.com/5375557/70662058-1df52d00-1c2b-11ea-999d-b02fc7b62d33.png">

Public Sans is supposed to support tabular numerals, where all numbers 0-9 have the same width, ensuring that a column of numbers is properly aligned.

Some columns of our tables specify tabular numerals. (And more would, if it weren't for this $@#&! font bug.)

Instead of appearing in Public Sans, they're appearing in a completely different font.

Why is this?

**Comment by cmgiven** [comment]
Here's what we want to see (the bottom image):

![public-numerals](https://user-images.githubusercontent.com/5375557/73676725-7ddfe100-467a-11ea-8b2f-bf4eddd7f46a.png)

I was able to confirm that Public Sans supports tabular numerals by opening the font in an Adobe application and enabling the OpenType feature.

I tried creating custom webfonts using Font Squirrel, replacing the USWDS-shipped ones, to ensure that the webfonts included tabular numeral support.

I think it appears incorrectly in all browsers.

There might have been some other head->desk that was lost to the sands of time.

**Comment by mmazanec22** [comment]
![not_included_default](https://user-images.githubusercontent.com/12260067/73749979-62ccaa00-472a-11ea-905b-2e7fdcb065eb.png)

https://github.com/uswds/uswds-site/pull/583
https://github.com/uswds/uswds-site/issues/575

:thinking:

**Comment by cmgiven** [comment]
Oh, huh, might this actually be working? Sorry for the wild goose chase, but I think what we have matches the text as shown above, no?

**Comment by mmazanec22** [comment]
Oh yeah I think it does-- didn't even notice that, was mostly puzzling over what "not included in default set" meant and noticing that even though that one issue seemed to say there would be instructions to change that, there aren't any.

But yeah that looks the same to me.  I think I'm going to make a PR to update USWDS and extend text-tabular rather than setting that ourselves and close this.
