### ISSUE TITLE
Completed steps in enrollment flow show wrong icon

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#409]
Should be a checkmark.

<img width="947" alt="Screen Shot 2019-12-12 at 9 38 15 AM" src="https://user-images.githubusercontent.com/5375557/70726144-37e24e80-1cc3-11ea-9365-a6e5cdd7e89b.png">

**Comment by cailyncodes** [comment]
This is an upstream bug that was fixed 23 days ago: https://github.com/uswds/uswds/pull/3232

We need to update 2.3.1
