### ISSUE TITLE
No ethnicity should be selected by default

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#413]
<img width="249" alt="Screen Shot 2019-12-12 at 11 56 53 AM" src="https://user-images.githubusercontent.com/5375557/70736771-a381e700-1cd6-11ea-87a5-1764f46f3da2.png">

Neither radio button should be checked when I first enroll a child. If I select "Not Hispanic," that should be a deliberate action.

**Comment by jlhogan** [comment]
does this mean that on the backend model, `HispanicOrLatinxEthnicity` should be nullable?

**Comment by cmgiven** [comment]
Yes, that's right. Looking now, realize this shouldn't be marked as UI.
