### ISSUE TITLE
Validate: start of first reporting period is before or the same as the withdrawn date

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#428]
**AC:**
- Validate that a child's withdrawn date is the same or later than any date within their first CDC reporting period (e.g., if report is Jan 1-Jan 31, they can withdraw no sooner than Jan 1)
- If not, show a standard red in-line error on save
- Copy [clarify placement]:
  - Date is earlier than child's enrollment
- Front-end blocked by need for withdrawal flow (ticket)
- Withdrawn date is later than beginning of first reporting period (ticket)

**Related:**
- Last funding period starts before withdrawn date
- Withdrawn date is later than beginning of first reporting period

**Comment by abbyraskin** [comment]
@cmgiven can you enroll and withdraw on the same date?

**Comment by cmgiven** [comment]
We know that’s a workaround for not being able to delete in ECIS. It seems unlikely that you’d actually want to do that. But I guess not impossible?

**Comment by abbyraskin** [comment]
This is now moot after talking to Julia. Closing.
