### ISSUE TITLE
Overutilization alert during enrollment

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#429]
**AC:**
- If a provider has filled all slots for a given age group in the current reporting period, display an alert letting the user know they will have used more spaces than are available.
- The alert logic is based on spaces allotted per age group (e.g., if the site has 12 preschool spaces, this alert shows if there are currently 12 children enrolled in a preschool space while a user tries to enroll a new child in a preschool space)
- Copy (note differs from design): 
  - This space type is already fully utilized for the [report period, e.g., January 2019] reporting period.

**Design:**
<img width="632" alt="Screen Shot 2019-12-17 at 2 18 21 PM" src="https://user-images.githubusercontent.com/30734760/71030970-1674ce80-20d8-11ea-8c27-6665100dbb1f.png">

**Comment by mmazanec22** [comment]
@abbyraskin do we want this for new and edit, or just new?

**Comment by abbyraskin** [comment]
Both, thanks.

**Comment by mmazanec22** [comment]
@abbyraskin another question coming up as I implement: do we want to display this only right after the user selects the funding to put it over the max (for new or edit), or do we also want to display this on load when a user is in edit view for an enrollment with an already-selected funding type that is past max?

To accommodate the latter case (where "already" wouldn't make total sense) maybe we could change the copy to something like "32 enrollments are using CDC full time funding for the January 2020 reporting period, but Site Name only has 30 spaces of this type." ?

**Comment by abbyraskin** [comment]
Yes! How about for the latter - "32/30 spaces are utilized for the January 2020 reporting period."

I'm keeping the definition of a space a little vague because they're allocated by age group in addition to funding (e.g., 30 part time school age spaces, which gets kind of long...).

**Comment by mmazanec22** [comment]
@abbyraskin so sorry to mire this further with more questions but: what if someone edits or creates an enrollment that will put them over that funding capacity for multiple reporting periods?  Like if they select several reporting periods ago and it messes up the last three?  Maybe alert components could have a "more details" type of function-- so that it shows the vague text but the user can dive deeper?

**Comment by abbyraskin** [comment]
I lean toward whatever is least complex for now (I don't think we need more details on the alert yet?), given that we don't know much about whether this is a scenario users will encounter frequently and I'd like to get more real world feedback first.
