### ISSUE TITLE
8-week grace period for non-CT birth certificates

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#432]
According to CDC contracts, providers have 8 weeks from the date of enrollment to provide non-CT birth certificates (so we can't block user from submitting a report without the non-CT birth certificate information for a child who has been enrolled 8 weeks or less?)

![image](https://user-images.githubusercontent.com/30734760/70841553-f5af2f00-1de0-11ea-9e87-d4e54a8e3ecc.png)

**Comment by abbyraskin** [comment]
Related, but different: are birth certificates required for SR sites?

**Comment by julyytran** [comment]
Moved to design board and combined with #314 for further research/design
