### ISSUE TITLE
Figure out missing information indicators for private pay children

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#443]

**Comment by abbyraskin** [comment]
we're hiding these missing information indicators for private pay for now - closing this out.

**Comment by jlhogan** [comment]
worth noting -- they're hidden in the roster and missing information count, but still show up in the detail view.

**Comment by abbyraskin** [comment]
thanks - in that case maybe i was too hasty/we should still revisit these in a future design sync

**Comment by abbyraskin** [comment]
Duplicate of #622
