### ISSUE TITLE
Family information collapsed state

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#451]
**AC:**
- After saving the "Family information" step, display in the collapsed view any of the address fields that have been entered (mimics behavior of the other sections) after a colon. If either of the checkboxes in this section have been selected, include the checkbox label in the collapsed state as well (otherwise only show address). For example:
- Address: 123 Main Street, Oak Park, IL 60302
- Child lives with foster family 
- Family has experienced homelessness or housing insecurity

**Comment by jlhogan** [comment]
RIght now the family info summary is only the address, and if the address is not fully populated it won't show anything. Not really a bug, just doesn't meet AC. If you could define what should be shown in the family info summary view, this is a trivial fix!

**Comment by abbyraskin** [comment]
Hm, I'm struggling to figure out exactly what's going on. If I enter the full address it only shows the city when collapsed. If I enter part of the address it seems to show the first letter.

**Comment by abbyraskin** [comment]
But I will add in AC with expected behavior (seemed like a bug because it was inconsistent between fields within the section and inconsistent from the other sections, my bad)
