### ISSUE TITLE
Backend work for missing information indicators

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#463]
This is a ticket for implementing the backend work of the missing information indicators, which tell a user that there is information that must be entered before they can submit their CDC report. All fields that are not optional, or that are not "hard" blockers during enrollment (name, site) trigger a missing indicator at various areas within the app (during enrollment, on the roster, on the child summary page).

**AC:**
- For CDC funded children, all fields that are not optional, or name and site (which block a user from continuing during enrollment) trigger missing information alerts. The following data fields trigger missing information if left empty:
- First name
- Last name
- Date of birth
- Birth certificate ID
- State
- Town
- Race
- Ethnicity
- Gender
- Address Line 1
- State
- Town
- Zip code
- Household size (unless family information not disclosed is selected)
- Annual household income (unless family information not disclosed is selected)
- Date of income determination (unless family information not disclosed is selected)
- Start date (enrollment.Entry)
- Age group (enrollment.AgeGroup)
- Funding type (pre-populates to "private pay" if family information not disclosed is selected)
- First reporting period (unless family information not disclosed is selected)
- If receives Care 4 Kids checkbox is selected:
  - Family ID
  - Certificate start date
- **note:** if a child is private pay, then the information above is not required for submitting the monthly CDC report (only the org/site name and child name, since those fields are required to save a child to the database at all).

**Related stories:**
- [Show missing info indicators on roster](https://github.com/ctoec/ecis-experimental/issues/308)
- [Show missing information indicators on child summary page](#461)

**Comment by abbyraskin** [comment]
take a peek when you have a chance - hoping this gets you what you need! (and please edit directly as needed)

**Comment by jlhogan** [comment]
all race booleans (`AmericanIndianOrAlaskaNative`, `Asian`, `BlackOrAfricanAmerican`, `NativeHawaiianOrPacificIslander`, `White`) are non-nullable and default to false, so all race fields will always have value.

**Comment by abbyraskin** [comment]
hm okay, so race is essentially optional? (we have race as required in our data collection document)

also, the design team discussed hiding the missing information indicators if the child is private pay but i need to confirm - is that something you'd want noted in this ticket or elsewhere?

**Comment by jlhogan** [comment]
re: hiding the indicators if private pay -- need a little more context to say. If private pay, then the informatoin is actually not required for submitting the report? in that case, then yes we want to know that here as we need to implement the validations such that they are conditional on private pay. If it's just a display thing, but you still need to put the informatoin in to submit the report (now that i'm typing that, seems vvvvvvvvvvvvv unlikely....) then that's a front-end concern.

**Comment by abbyraskin** [comment]
essentially the former. if they're private pay the only information required is the information required to create the child record (name, site). they could submit a report even if there are private pay kids with any other information left blank (except, obviously, the fact that they're private pay which we'd need to know). so yeah, we'll need some conditional logic - will add a note in the AC.

as far as the front end, for now we'll show the indicators consistently regardless of whether they're private pay, and if we decide to add some different logic there, sounds like those would happen under front end tickets separate from this one.

**Comment by jlhogan** [comment]
if i need to add the logic to the backend, then the alerts just won't be generated for private pay entities and so they won't show up in the front end either :) 

perhaps stupid question: How are we denoting if a child in an enrollment is private pay ?

**Comment by jlhogan** [comment]
for now our thinking about how to deal with validations on private-pay enrollments: we will still generate all validation rules for private pay enrollments, however at the report level, we can create a rule like `FundedEnrollmentsAreValid` to allow reports to be submitted, even if the org/site includes private pay enrollments that are missing information

NOTE: this only works if it's ok for private pay enrollments to have _any_ non-blocking validation errors.

**Comment by jlhogan** [comment]
```If receives Care 4 Kids checkbox is selected:

    Family ID
    Certificate start date
``` 
what does `start date` refer to here?

**Comment by abbyraskin** [comment]
yes, that's right - basically Care 4 Kids sends a certificate with a date that indicates when a provider will start receiving payments for a kid, and it has to be renewed every year. the family id/case number is a unique ID assigned by Care 4 Kids (usually on a family basis if there are multiple children but it seems like they may be occasional exceptions).

**Comment by jlhogan** [comment]
this is at least mostly done. will open new tickets as we ID more validations.
