### ISSUE TITLE
Validate: end of first reporting period is after or the same as enrollment date

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#470]
**AC:**
- Validate that the last day of the child's first CDC reporting period is the same or after the child's enrollment date (e.g., if the start date is January 1, the reporting period can't be earlier than Jan 1-Jan 31; a child CAN enroll earlier than the funding/reporting start date)
- Error highlights enrollment date field ("Start date") with following copy:  
  - Reporting period must be after start date

**Comment by cailyncodes** [comment]
I think the error message should be: "Start date cannot be later than end of first reporting period" ?

**Comment by abbyraskin** [comment]
@cailyncodes i just updated the AC after thinking about this more, i think it makes sense to validate on the reporting period rather than the start date (Reporting period must be after start date), sorry for the confusion.
