### ISSUE TITLE
Roster legends/tags should only use current fundings

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#498]
Fundings are time-bound; they apply only for a certain period. Currently, the roster legends and tags look only for the presence of a funding on an active enrollment. They should be looking only for active fundings, that is those fundings whose first/last funding periods overlap with the date range being shown by the roster.

**AC: **
* When the roster is showing only current enrollments, a funding with a last funding period that ends prior to today should not be shown as receiving funding. A funding with a first funding period that starts in the future should not be shown as receiving funding.
* When the roster is showing past enrollments, any enrollment that has a funding period that overlaps with the roster's date range should be shown as receiving funding.
* When a funding has no last funding period, it should be assumed to extend indefinitely into the future.

(I don't believe this should be considered pilot-critical.)

**Comment by jlhogan** [comment]
perhaps we should do some of this filtering in the backend -- only returning current fundings unless others are specifically requested, and maybe then extending the enrollment model with a `PastFundings` array depending on how this data would need to be used

**Comment by cmgiven** [comment]
Oh, that's a good idea. I don't think we have a need for `PastFundings`, so it's probably sufficient to have the option of getting everything or just getting the active stuff.
