### ISSUE TITLE
Ethnicity has UI default but shows warning that field is required

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#510]
![Screenshot from 2019-12-30 13-37-00](https://user-images.githubusercontent.com/12260067/71595420-88520c80-2b09-11ea-81b4-b42801b6ef87.png)

**Comment by cailyncodes** [comment]
This looks like there was a regression of https://github.com/ctoec/ecis-experimental/issues/413

**Comment by abbyraskin** [comment]
closing in favor of https://github.com/ctoec/ecis-experimental/issues/542
