### ISSUE TITLE
Azure Release Pipeline (dev) - Extend to perform AWS RDS and Beanstalk deployments

### ISSUE THREAD

**Issue by speedcm** [ctoec/ecis-experimental#52]
Extend the Azure Release Pipeline to deploy to AWS RDS and Beanstalk.  This effort is for the Development release pipeline. 

This issue is dependant on Github issue #50

**Comment by speedcm** [comment]
This issue is now complete.  The Azure DevOps 2019 release pipeline (dev) was updated to deploy to AWS beanstalk and AWS RDS. A successful deployment was done for Azure Release build 44.  For more information, see the hedwig project in Azure. The hedwig app is accessible on AWS Beanstalk via http://hedwig-env.xm53wc3xxw.us-east-2.elasticbeanstalk.com/

**Comment by Pravish88** [comment]
Hello,
Is there any documentation on how to deploy to AWS RDS?
