### ISSUE TITLE
Inconsistent spacing

### ISSUE THREAD

**Issue by cailyncodes** [ctoec/ecis-experimental#522]
Inconsistent spacing throughout enrollment flow

<img alt="Screen Shot 2020-01-02 at 9 03 34 AM" width="421" src="https://user-images.githubusercontent.com/7797826/71670743-e1ef4c80-2d3e-11ea-9caa-43ca11967308.png">

**Comment by mmazanec22** [comment]
Looks like these issues have been fixed.
