### ISSUE TITLE
A completed section 1 still shows “incomplete” at the section

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#531]
**Description of issue:**
- If all required information in the first section of enrollment (child information) is complete, there is still a "missing information" indicator on save
- This might be related to the ethnicity field - I noticed if you don't select an ethnicity during enrollment, on save the field is highlighted with a missing information validation with a selected radio button (in the screenshot below, I had left "ethnicity" blank before saving)

**To reproduce:**
1. Add all required information to the first section of enrollment (child information) and save
1. (See incomplete indicator at section level)

<img width="1037" alt="Screen Shot 2020-01-03 at 11 10 34 AM" src="https://user-images.githubusercontent.com/30734760/71737585-ad03f800-2e19-11ea-8137-4e63e1a520cc.png">

**Comment by jlhogan** [comment]
This is due to the validation on FamilyId. don't love the idea of adding logic to the `sectionHasValidationErrors` to explicitly skip this. _Could_ add logic to skip all sub-object validations Will need to add some indicator to the `validationError` model to capture this.
