### ISSUE TITLE
Report should jump focus to first field with error if submit fails

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#535]
**AC:**
If a report is submitted and fails, jump the focus to the first field with an error

**Comment by mmazanec22** [comment]
According to Deque, we should move focus to the first form control with an error: https://www.deque.com/blog/anatomy-of-accessible-forms-error-messages/

**Comment by abbyraskin** [comment]
Yes, sorry, writing quickly (I was thinking we had a universal alert for the submit failing, wasn't thinking about the fields being empty!)- updated! Thanks!
