### ISSUE TITLE
"Family income determination" section is not saving and blocks if you remove info

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#536]
The "Family income determination" section of enrollment is not saving when any part of the section is filled out. After deleting the information from this section, users receive a blocking error and cannot proceed.

**Expected behavior:**
- If a user enters all information into this section, allow them to save and continue
- If a user enters information into this section, display a validation error if other information is left blank
- If a user deletes information from this section (so it is blank), they can still proceed.

**To reproduce:**

Initial save:
1. Add information to the "family income determination" section of enrollment
1. Try to save (doesn't work)

After deleting:
1. Delete information entered in this section
1. See validation errors (screenshot below)

![image](https://user-images.githubusercontent.com/30734760/71738868-821ba300-2e1d-11ea-87a5-f5fb5c6f7565.png)

**Comment by jlhogan** [comment]
getting to bullet point 3 of expected behavior means doing the same array update logic we have for fundings with family determination arrays

**Comment by abbyraskin** [comment]
This is done (closing) - we'll need a separate ticket for improving how we store redetermination history on the backend.
