### ISSUE TITLE
deal with ethnicity selection

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#542]

**Comment by abbyraskin** [comment]
looks like Melanie previously created a ticket - pasting the link here for reference (and closing that one out)

https://github.com/ctoec/ecis-experimental/issues/510

**Comment by cmgiven** [comment]
Oops. Missed it!

**Comment by jlhogan** [comment]
so this is a weird one, b/c the problem is that `hispanicOrLatinXEthnicity` is `undefined` but we're assuming it will be null. @cailyncodes thoughts? since you are the brains behind `DeepNonUndefinable`

**Comment by cailyncodes** [comment]
When we assemble the params to send to the server, we reconvert everything from null to undefined. So maybe we are accidentally reusing that object instead of the response from the server? (This is a first thought -- haven't actually looked at the code yet)

**Comment by cailyncodes** [comment]
I think I found it! `mutate` in `Section` type is of type `Mutate<Enrollment>` so values that aren't present are treated as undefined (per `Enrollment` type) as opposed to null (`DeepNonUndefineable<Enrollment>`)
