### ISSUE TITLE
Spacing and styling fixes

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#544]
(Pasted from the [QA list](https://docs.google.com/document/d/1qLIojSyekdx2yKJZjchPtQfjnndT1LK-k0qWVTDkGdw/edit?folder=1m5jgRSeZRdvTj-Ny8c0_tZW5YirMvp2P) - please pair with a designer if additional context is needed!)

**Spacing**
- Fix spacing for roster filters when selected
- Section 2 - too much spacing
- Section 3 & 4 - not enough spacing
- Spacing between missing/warning info is too much, generally just make other sections consistent with section 1, make spaces between headers and content consistent
- Income determination not disclosed spacing is weird
- Width seems weird and narrow generally, but sometimes isn't-- is that on purpose?

**Styling**
- Yellow for missing information icon is not correct: #C2850C - gold 40v
- Dropdown boxes are missing a right border on Windows (Chrome)-- see if this is us, if it's a USWDS bug then leave it
- Field errors (see c4k on save with missing id) should have properly spaced title (or none at all? generic?)
- Color contrast on cancel button in enrollment withdrawal

![Screen Shot 2020-01-03 at 2 28 08 PM](https://user-images.githubusercontent.com/30734760/71747447-44c30f80-2e35-11ea-9900-78f5acd864f6.png)

**Comment by mmazanec22** [comment]
Addressed by #568
