### ISSUE TITLE
State should be dropdown (CT, MA, NY, RI) and flip placement of fields

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#547]
To receive CDC funding, children can only live in one of 4 states, so we should restrict the dropdown in the address section to make it easier to accurately enter this data. Because town is typically entered before state, we should collect this data first.

**AC:**
- For a child's address (under "family information), change the state field to a dropdown with CT, MA, NY, RI (and the standard empty -Select- option set by default)
- Reverse the order/location of the town and state fields (town first, then state)

**Comment by mmazanec22** [comment]
@abbyraskin do we want state and town flipped for the child info section too?

**Comment by abbyraskin** [comment]
yes, thank you!

**Comment by mmazanec22** [comment]
Closed by #653
