### ISSUE TITLE
Prevent withdrawal of child with missing information

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#556]
To encourage complete/high quality data entry, and to prevent a user from a situation where they can't submit a report because they're missing information for a kid who's no longer on their roster, we should alert users to update missing information before withdrawing a kid.

**AC:**
- If a user tries to withdraw a funded kid with missing information (selects "Withdraw" button), display an alert at the top of the child's summary page, blocking the user from withdrawing any incomplete enrollments.
- This alert replaces (and encompasses the intent of) the current alert, which notifies users that they need to enter an enrollment start date.
- Red alert 
  - Header: Information needed to withdraw child
  - Body: 
     > To withdraw a child from a funded space in your program, they cannot have any missing information. Please enter all missing information indicated below to withdraw this child.

**Comment by abbyraskin** [comment]
Ignoring this ticket for the time being, per storytime.

**Comment by cmgiven** [comment]
Can we change this to: "Prevent withdrawal of child with missing information"? I'd imagine clicking the withdrawal button on a funded child with missing information leads to a page asking to correct the information before withdrawal.

**Comment by abbyraskin** [comment]
Just to verify - we should block withdrawals on any incomplete enrollments (if child is in a funded space), (similar to blocking report submission)?

**Comment by cmgiven** [comment]
That seems reasonable to me. That'll also prevent someone from getting in a position where they can't submit a report because they're missing information for a kid who's no longer on their roster.

**Comment by abbyraskin** [comment]
Okay, but we'll allow previous withdrawals that were "incomplete"? Just trying to think through the onboarding consequences if a bunch of children need to be withdrawn and have missing information. (Also could be a bit hairy in a world where this is happening in batch, but perhaps the new preview actions will make this easier to follow)

**Comment by cmgiven** [comment]
Yeah. I think the key thing is to head off withdrawn incompletes that you’ll need to include on your next report. If the historical data is incomplete, I don’t think there’s much to do about that.
