### ISSUE TITLE
Save silently fails after first or last name deleted in enrollment edit

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#563]

**Comment by jlhogan** [comment]
i just tried to repro this, interested to know more

**Comment by cailyncodes** [comment]
Might be related to #421 ??

**Comment by mmazanec22** [comment]
@jlhogan when I edit an existing enrollment and delete the first name and then press save, nothing happens and no errors appear-- haven't checked latest master so if you can't reproduce maybe it was fixed and I'm not aware?  Also @cailyncodes  that seems likely!

**Comment by jlhogan** [comment]
confirmed cannot repro
