### ISSUE TITLE
Copy update: "Cannot withdraw" alert

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#572]
We currently have placeholder text for the alert that shows on the withdraw page if a child is missing a first reporting period. 

Updated copy is included below:

**Header:**
Information needed to withdraw child

**Body:**
To withdraw a child from a funded space in your program, “first reporting period” cannot be blank. Please update this information for the child before withdrawing.

**Comment by abbyraskin** [comment]
@jlhogan updated copy as discussed yesterday when you have a moment

**Comment by jlhogan** [comment]
done!
