### ISSUE TITLE
Issues with the Update roster alert on reports (not recognizing changes?)

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#574]
Incomplete enrollments - are these children part of the reports list?

**Comment by mmazanec22** [comment]
Possibly related to #421 or #557 ?

**Comment by mmazanec22** [comment]
Maybe kids with no enrollment date are preventing?

**Comment by jlhogan** [comment]
I'm not sure this issue exists on it's own any more. A bunch of weirdness around unclear validations was resolved by fixing the empty string problem. However, it is true that private pay enrollments will NOT count towards report enrollments, but will show missing info indicator in the roster, which could be confusing for a provider trying to get everything in order for reporting.

on the backend, we don't distinguish between "doesn't have fundings yet" and "explicitly designated private pay" (which may be related to the conversation @abbyraskin  and @cailyncodes were having earlier?) 

I believe a good helpful step here would be to skip roster icons for private pay enrollments?

**Comment by cailyncodes** [comment]
Was indeed related to the convo @abbyraskin and I were having
