### ISSUE TITLE
[Week of Jan 13] Add Wallingford users to wingedkeys

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#591]
We have one additional site launch on Jan 21 at Wallingford, with two employees who will need credentials.

See user names [here](https://docs.google.com/spreadsheets/d/1cxw_sEwsumhkjyGin1jPbQHt5IjU46p5vuYwplmT1cI/edit?folder=0AHrWNRCNY10TUk9PVA#gid=1511878788).

**Comment by cailyncodes** [comment]
Users added

**Comment by abbyraskin** [comment]
@cailyncodes i'm not able to log in as jessica, I receive an invalid username/password error. for tamarah, i can log in, but do not see any data (but perhaps there is separate work happening to populate the site data still?)

**Comment by cailyncodes** [comment]
I'll look into the issue with Jessica. I didn't connect them up to Hedwig -- @cmgiven Does that data exist in the db? If so, I'll set the permissions

**Comment by cmgiven** [comment]
It doesn’t yet. I’ll load it now and Slack you the org ID. (Or you can send me the winged keys ids.)

**Comment by cailyncodes** [comment]
Either or works for me -- the WingedKeys ID have been added to lastpass

**Comment by cmgiven** [comment]
Cool, I'll hook 'em up. The ETL script has a function for it.

**Comment by cailyncodes** [comment]
Ooh yes, script is much better than me manually editing the db

**Comment by cailyncodes** [comment]
@abbyraskin I fixed the login for Jessica. (We only have the password hash for the wrong credentials so we'll never know I accidentally entered the first time.) Also it looks like Chris entered the program data, so it should be all set
