### ISSUE TITLE
Create December CDC reports for Annette [Due 1/17]

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#601]
- Use the data entered by pilot sites to create a spreadsheet for Annette that mimics the existing PSR (empty "prototype" [here](https://docs.google.com/spreadsheets/d/17vUYiA1OmXKa2zy6Z52nfSXrl1QgSA5UaTAOZOTLrz8/edit#gid=295472504))
- We should send all 4 to Annette at once.

**Comment by cmgiven** [comment]
[Script is done.](https://github.com/ctoec/ecis-data-migration/commit/b76056bebfdf57ee42f2d6333de8be7fb67c8e94) The three sites that have submitted have been generated and spot-checked. Can generate the remaining one once they submit.

**Comment by abbyraskin** [comment]
Woot. I'll check in with Mount Olive tomorrow.
