### ISSUE TITLE
Discuss Frontend Testing Framework

### ISSUE THREAD

**Issue by cailyncodes** [ctoec/ecis-experimental#605]
Developing front-end/browser tests seem to be an important concern now that the pilot has launched. This issue will track requirements we need and possible solutions.

**Comment by cailyncodes** [comment]
Selenium (https://selenium.dev/) is a very common solution to browser based testing

**Comment by cailyncodes** [comment]
More resources:
* https://selenium.dev/documentation/en/introduction/on_test_automation/

**Comment by cailyncodes** [comment]
Proposal:
* Unit-like tests for our containers (probably does NOT need browser driver, Jest should do)
** Enrollment flow and detail has proper missing info/complete icons
** EnrollmentFunding gives CDC reporting period dropdown of 3/4 options ordered by date
** Roster has proper missing info icons
** Roster renders children in age-separated sections
** Report Summary lists pending and submitted reports separated by time correctly
** Report Detail prevents submit on missing info
** Report Detail has correct counts
** Alerts appear where necessary
** Roster date filtering
* Integration-like tests (probably need a browser driver like Selenium)
** Logging in
** Submitting report updates report summary
** Enrolling a child updates roster
** Canceling enrollment returns to roster with no new child

**Comment by mmazanec22** [comment]
On the unit end of the spectrum: seems like the primary alternative to Enzyme is React Testing Library.  My frustration with Enzyme has been that mount doesn't seem to render as deeply as the documentation would indicate, so if another library could allow us to ditch our chains of find/dive, I would support that.  Looking for documentation about testing components using newer React features (i.e. hooks), it seemed like React Testing Library is quicker than Enzyme to respond to changes in the React API.

**Comment by mmazanec22** [comment]
This could be useful to help us catch some accessibility issues (though, as the README notes, automated tools are limited): https://github.com/nickcolley/jest-axe

**Comment by mmazanec22** [comment]
Decided in 1/30 dev meeting:

- Set up React Testing Library so that new tests can be written with that
- Convert old tests from Enzyme to RTL
- Add non-blocking accessibility checker, set up a slack reminder to discuss it later
- Add Selenium eventually, soon-ish because browser/date things are ridiculous

**Comment by cailyncodes** [comment]
Closing as decision has been made.
See #681, #682, #683, #684
