### ISSUE TITLE
Missing information icon shows in summary on complete enrollment/funding section

### ISSUE THREAD

**Issue by cailyncodes** [ctoec/ecis-experimental#622]
But only when there is a CDC funding (private pay not affected)

**Comment by jlhogan** [comment]
any more details for specific data/state for repro?

**Comment by cailyncodes** [comment]
Steps:
1. Fill out the enrollment form (only first name and last name)
1. Add a CDC funding with age group, start date, and reporting period
1. Hit save

Expected
1. Missing info shows up on section 3 (family income b/c there is a CDC funding)
1. No missing info shows up on section 4

Actual
1. Missing info shows up on section 3 (family income b/c there is a CDC funding)
1. Missing info also shows up on section 4
