### ISSUE TITLE
Add margins to the bottom of pages so date picker is always visible when active

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#627]
We noticed during the pilot launch that the calendar date picker displayed off-screen when scrolled. 

**AC:**
- Add margins to the bottom of pages - enough room to accommodate a date picker

**Comment by mmazanec22** [comment]
@abbyraskin where is this an issue?  I'd like to recreate it to make sure I'm fixing it

**Comment by abbyraskin** [comment]
Sorry the story isn't clear, let me double check. I think it happened during enrollment.

**Comment by abbyraskin** [comment]
Could it depend on monitor size/OS? I can't reproduce it. @victoriasuwardiman do you know more here? we definitely saw it over someone's shoulder...

**Comment by mmazanec22** [comment]
If we generally just want a sizable margin to avoid shenanigans that can be arranged.  Related: do we have any plans for a footer?

**Comment by victoriasuwardiman** [comment]
I can't recreate either but yeah we did see it watching someone else enter a date, during enrollment. I think the monitor was pretty small so definitely might be dependent on resolution.

**Comment by abbyraskin** [comment]
Sizable margin sounds good for now, thank you. We haven't discussed a footer yet, but I'll add a placeholder to the backlog for discussion with design folk (assuming you don't need specific direction on footer now as part of this work).
