### ISSUE TITLE
Azure - Azure DevOps Services Setup - Organization

### ISSUE THREAD

**Issue by speedcm** [ctoec/ecis-experimental#63]
1. Sign into Azure 
- use your skylighthq.onmicrosoft.com account

2. Setup an Azure DevOps Services Organization for skylight
Follow these instructions
- https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/create-organization?view=azure-devops

Notes:
- The user that sets up the organization is the organization owner

3. Setup Azure DevOps Organization Billing

Follow these instructions
- https://docs.microsoft.com/en-us/azure/devops/organizations/billing/set-up-billing-for-your-organization-vs?view=azure-devops

4. Add Users to the Azure DevOps Organization

Follow these instructions
- https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-organization-users?view=azure-devops&tabs=browser

5. Add Users to Project Collection Administrators

- Select Organizational Settings -> Permissions -> [Organization-Name]Project Collection Administrators
- Select Members->Add

Notes: 
- Members of this application group can perform all privileged operations on the Team Project Collection

**Comment by cmgiven** [comment]
@speedcm I believe this is done. Can you confirm?
