### ISSUE TITLE
Accredited checkbox is unchecked during printing a submitted report for the first time

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/ecis-experimental#635]
May only happen after initial login. 
OS: Windows 10
Browser: Google Chrome

Steps to recreate (see video capture: https://drive.google.com/open?id=1-llICthHieo2Lq-juphYF6bii_Anxbyb)
1. Login to staging
2. Go to reports tab
3. Go to October 2019 report
4. Click Print
5. In the print preview, the accredited checkbox is unchecked
6. Close print dialog
7. Click Print again
8. In the print preview, the accredited checkbox is checked

**Comment by abbyraskin** [comment]
Just noting that I think we might have originally theorized that this was a Windows specific issue, but I noticed it on my Mac today as well.

**Comment by abbyraskin** [comment]
From planning today: bug still occurs if the report is a draft.

**Comment by mmazanec22** [comment]
I think it's not draft related, but related to loading SVG the first time you attempt to print.  I can no longer recreate in FF or Chrome on my machine so I'd love to pair with someone who's seeing this bug.

**Comment by cmgiven** [comment]
✋ Sometime tomorrow?
