### ISSUE TITLE
Split reports (mega ticket)

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#636]
A "type" of slot is defined as:
- Age group + time (split or entirely PT or FT, totaling some # of weeks?)
- Roster tags are shown only if a user has multiple slot types for a given age group

***
Story definition in progress (to be broken into smaller tickets):

Minimal stories for first iteration (launch to New Milford):
- In enrollment, change "funding" section options to radio buttons
- If a program has a split age group for its CDC funded kids, e.g., ~the same number of slots assigned to a group, for a differing numbers of weeks per year totaling 52 weeks - and it is the only option available for that age group...
  - Under Funding, after selecting an age group, display only one Time option, with copy that tells users how many weeks are allocated to each, listing the option with more weeks first. e.g.,:
    - Part-time (41 weeks) / full-time (11 weeks)
- If a program age group has only one time slot available for its CDC funded kids, a user does not need to specify the time
  - After selecting the age group, display the time/weeks as text beneath the radio button label
     - e.g., full-time (52 weeks)
- On the roster, the funding tag should just say "CDC", unless there are multiple slot types per age group (if there is only one split slot type, with a mix of PT and FT weeks, it still only says CDC)
- If a program has a split slot type, with at least one enrollee assigned to that slot type on the roster for that report:
  - Add a field to enter the # of weeks
     - Default text box value to 0
     - Label: "[Time] [Age group] services were provided" (e.g., Full-time preschool services were provided)
      - Include the number of weeks in that month's report 
      - Include the current report month
      - Include the # of weeks remaining for the year, for the time option with fewer weeks
- On the report, if a user has entered 1 or more weeks in the split box above, update the table to show the breakdown of full-time/part-time weeks 
- [OEC report: update the script/figure out layout for spreadsheet]

Later:
- Validate a number is entered
- If they don't have any weeks remaining...
- Language for time: full year, school break, etc.

# Example from pilot contract
Contract looks like this:
5 Spaces of full-time infant and toddler care  - 52 wks
26 Spaces of full-time preschool care - 52 wks
16 Spaces of full-time school-age care - 11 wks
16 Spaces of part-time school age care - 41 weeks

**Comment by abbyraskin** [comment]
Schedule post-standup discussion next Thurs.

**Comment by abbyraskin** [comment]
Potentially pull off data schema changes.

**Comment by abbyraskin** [comment]
@cmgiven this is the megaticket in progress fyi

**Comment by cmgiven** [comment]
Ah, shoot, I couldn't find this. Have been working on #889.

**Comment by abbyraskin** [comment]
Closing in favor of https://github.com/ctoec/ecis-experimental/issues/889
