### ISSUE TITLE
Birthdate/age validations

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#642]
Other note from Annette: "Note that CDC is complicated by the fact that there are about a dozen programs that provide school-age care – which can throw everything else off, as there are age limits in the other categories that could be overlooked by this variable."

Seems the rules could be (pending discussion around if/how we want to implement more precisely)??:
- If enrolling in FT or PT infant/toddler program, child cannot be younger than 6 weeks or older than 3 years
- If enrolling in FT preschool program, child cannot be younger than 3 or older than 6; can be enrolled as 2 year old if they turn 3 during Sept-December (and start in a funded slot during one of those months)
- If enrolling in school age, child cannot be older than 12 years

- related to #462

**Comment by cmgiven** [comment]
![image001](https://user-images.githubusercontent.com/5375557/72635536-a77ed580-3922-11ea-8608-839860220901.png)

**Comment by cmgiven** [comment]
(From Annette.)

**Comment by abbyraskin** [comment]
Other note from Annette: "Note that CDC is complicated by the fact that there are about a dozen programs that provide school-age care – which can throw everything else off, as there are age limits in the other categories that could be overlooked by this variable."

Seems the rules could be (pending discussion around if/how we want to implement more precisely)??:
- If enrolling in FT or PT infant/toddler program, child cannot be younger than 6 weeks or older than 3 years
- If enrolling in FT preschool program, child cannot be younger than 3 or older than 6; can be enrolled as 2 year old if they turn 3 during Sept-December (and start in a funded slot during one of those months)
- If enrolling in school age, child cannot be older than 12 years

**Comment by julyytran** [comment]
Combining with #462
