### ISSUE TITLE
Standardize date picker

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#643]
Users reported a desire for consistency across date fields. We should use the date picker everywhere we ask for a date in the application, with the option or show or hide the calendar view.
- Combine DateInput and DatePicker into a single component with consistent design and validation
- Handle two digit years when typing.

**Comment by abbyraskin** [comment]
@cmgiven can you help with what's needed here?

**Comment by mmazanec22** [comment]
This is good to know-- we were using the calendar dropdown everywhere but some concerns had been raised about entering things like birthdate, for which a calendar dropdown isn't that great.  Right now the date input component implements USWDS recommendation and the calendar dropdown is from Airbnb.

The calendar dropdown poses a few challenges, mainly that we don't have complete control over how it looks and behaves, especially when a user types an invalid date, or when we need to associate an aria label (like a hint or error) with the input field.

It sounds in the quoted text like a hybrid approach is what we're after?

**Comment by cmgiven** [comment]
Yes! As you note, we now have some varied examples of what we need from a date picker component. So the tech debt angle is to combine DateInput and DatePicker into a single component with consistent design and validation, like there's an option to show the popup or not.

I think the unmet user needs that I've seen are:

* Some users use the mouse constantly. They love to use the dropdown, provided the date is recent. Obviously years-old dates don't work with the dropdown. When these users hit the three fields, though, they do not tab between them, and they dislike that they have to click into three different fields. They'd love to just type slashes and have the field figure out what to do.
* We'd love to be able to handle two digit years when typing.

**Comment by cailyncodes** [comment]
Closed by #796
