### ISSUE TITLE
organization enrollments endpoint

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#651]
user story: As an API consumer I want to retrieve enrollments for all sites in a given organization

**AC**:
- can retrieve enrollments for multiple sites in a given organization through route like:
`/api/organization/{id}/enrollments`

**Comment by jlhogan** [comment]
After playing around with implementing this, I think it may be better to just make the change in the frontend to make multiple simultaneous queries for per-site enrollments... not the most optimized but keeps the access/permissioning and the dotnet niceness with routes simple

**Comment by cailyncodes** [comment]
Jk we do need this

**Comment by cailyncodes** [comment]
Closed by #699
