### ISSUE TITLE
Multi-site roster view

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#652]
User story: As a provider from a multi-site organization, I want to be able to optionally view a multi-site roster, or view a site-specific roster

**AC**:
- can view all enrollments for all sites (default)
- can view enrollments for a single site by selecting the count of sites link (see design), which displays a dropdown of sites belonging to the program organization
- the single-site view includes a "Back to program roster" link (note: program should not be capitalized) to return to the combined multi-site roster 
  - back button in browser also returns user to combined roster view

**Design:**

## Multi-site roster view (combined)
<img width="1067" alt="Screen Shot 2020-02-18 at 4 50 34 PM" src="https://user-images.githubusercontent.com/30734760/74781084-dc0de600-526e-11ea-8d4b-65ac3e0ef72c.png">

## Dropdown with list of sites
<img width="910" alt="Screen Shot 2020-02-18 at 4 55 11 PM" src="https://user-images.githubusercontent.com/30734760/74781416-70784880-526f-11ea-9d34-5de37e90fcd6.png">

## "Back to roster" roster view after selecting individual site
<img width="576" alt="Screen Shot 2020-02-20 at 6 04 41 PM" src="https://user-images.githubusercontent.com/30734760/74988296-7b67e000-540b-11ea-98ba-33e2609ddbcf.png">

**Comment by abbyraskin** [comment]
@cailyncodes small AC change incoming (affects the second step) - will update after storytime momentarily.

**Comment by cailyncodes** [comment]
Sounds good! There are some other things I need to figure out first before I really dig into implementation

**Comment by abbyraskin** [comment]
Up to date!
