### ISSUE TITLE
require FamilyFees on CdcReport

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#674]
**AC**
- FamilyFees field is required on backend model
- UI correctly displays server errors if post fails due to missing familyfees

**Comment by mmazanec22** [comment]
Also add optional to c4k-revenue TextInput

**Comment by jlhogan** [comment]
@mmazanec22 do any tests need to be updated/un-commented?

**Comment by mmazanec22** [comment]
I think I had started into one with some faulty assumptions about required fields and then deleted it so as not to merge junk in with the other PR.  Maybe another pass at report tests for more thorough coverage can be an after-test-conversion task?
