### ISSUE TITLE
Update report generator task to create reports for any past reporting period w/out one

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#694]
**AC**
- past reports are created iff they do not yet exist
- "past reports" = reports for reporting periods with periodEnd <= today (in the past)

**Comment by cmgiven** [comment]
Maybe we should only create past reports that are newer than an existing report, though? Because a program that onboards now, we don't want to create reports for them back to the beginning of time.

**Comment by jlhogan** [comment]
so does that mean when onboarding a new program, a requirement is the creation of their first report

**Comment by cmgiven** [comment]
Good point. It could.

Or maybe the simplest is just to write it to only test the last reporting period (you had suggested this in Slack).
