### ISSUE TITLE
Withdrawn reason validation fails for multiple enrollments

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#709]
If a child has been enrolled in multiple programs, we should only require withdrawn reason on the withdrawn enrollment (it appears we're validating for all enrollments)
- Example in staging: Chris Rankin

**Comment by jlhogan** [comment]
@cmgiven @abbyraskin -- this is not actually a bug in the data validations; the seed data was creating invalid enrollments. There is no data in prod in this invalid state (exit != null, exitreason == null):
```
julia@ip-10-0-10-170:~$ ./prod-db                                                                         
1> select count(*) from enrollment where [exit] is not null and exitreason is null                        
2> go                                                                                                     
                                                                                                          
-----------                                                                                               
          0                                                                                                                                                                                                    
```
my impulse here would be to just fix the seed data, as this validation is actually functioning as intended

**Comment by cmgiven** [comment]
Oh yeah, agreed. Sorry for the goose chase. Although I think #710 is still useful.

**Comment by jlhogan** [comment]
agree! ty
