### ISSUE TITLE
Visible keyboard focus on header/logo

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#725]
There is no visible keyboard focus on the logo/ECE Reporter text (https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=132#focus-visible)

**Comment by cmgiven** [comment]
@mmazanec22 Does this need AC/design love, or is this ready to go?

**Comment by mmazanec22** [comment]
I imagine the ideal would be that focus looks the same way as it does for everything else and works consistently in each browser, and if that's not possible then probably we need some design decisions.

**Comment by cmgiven** [comment]
Yup. I'll move it into current sprint, and if we need others' eyes, we can loop 'em in.
