### ISSUE TITLE
Fix spacing of family fees error on report

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#727]

**Comment by jlhogan** [comment]
I cannot confirm if this is still an issue. Error looks like this now:
![Screenshot from 2020-04-10 16-56-11](https://user-images.githubusercontent.com/54035880/79022544-32e7bb80-7b4c-11ea-9818-90d18e8414af.png) @mmazanec22 thoughts?

**Comment by jlhogan** [comment]
From slack:

> Melanie Mazanec
Yeah it's fixed, was all weird and off to the left before.  Probably we should revisit some formatting things after we merge the form component
