### ISSUE TITLE
Updated research plan

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#73]

**Comment by victoriasuwardiman** [comment]
[Hedwig Usability Testing/Pilot Plan](https://docs.google.com/document/d/1Ds0qSD7oJDISNybFvfoYiI_t7Dxo5uW6JA75g3iGy7A/edit#heading=h.mtxqzrn48e6l)

**Comment by victoriasuwardiman** [comment]
Usability Testing (Round III) Schedule:
Tues, 10/15 @ 10am
Wed, 10/16 @ 2pm
Thurs, 10/17 @ 10am
Thurs, 10/17 @ 1pm
