### ISSUE TITLE
Add enrollment history to Enrollment Detail (V1)

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#735]
User story: As a user, I want to see a timeline of important events in the history of a child, including all enrollments

**AC**:
- Events are displayed in timeline with dates 
- Events with dates < 1 week ago get `NEW` tag 

Event copy:
- Enrollment start, first enrollment for child:
```
Enrolled in <Program Name>
On <Month, Day, Year>
```
  - Enrolment start, Nth enrollment for child:

```
Changed enrollment to <Age group> in <Program Name>
On <Month, Day, Year>
```
  - Funding started: 
```
Updated funding to <funding, time>
On <Month, Day, Year>
```
  - Funding ended, and no next funding:  
```
Updated funding to private pay
```
  - New income determination
```
Income redetermined
On <Month, Day, Year>
```
(NOTE: this will require checking all enrollments for the child for presence of a c4k funding; in the future i'm hoping we move c4k certs onto the child object)
  - C4K Cert added , first cert for child
```
Care 4 Kids certificate added 
On <Month, Day, Year>
```
  - C4K cert added, Nth cert for child 
```
Care 4 Kids certificate renewed
On <Month, Day, Year>
```
  - Enrollment end: 
```
Withdrawn from <Program Name>
On <Month, Day, Year>
```
![Screenshot from 2020-03-13 10-08-53](https://user-images.githubusercontent.com/54035880/76628126-aa590980-6512-11ea-9940-601c22604842.png)

**NOT AC**:
- author info

**Comment by abbyraskin** [comment]
@jlhogan we held off on changing/working this story - I think you had a sense of the additional work left here (re: the open questions we discussed in last design sync), but let me know if you want to sync up.

**Comment by abbyraskin** [comment]
Notes from storytime: for now, limit to date the change happened - don't need to say which user made the update.
