### ISSUE TITLE
Implement Sentry in Hedwig Client Source

### ISSUE THREAD

**Issue by speedcm** [ctoec/ecis-experimental#751]
Sentry has been implemented in the Hedwig backend and needs to be implemented in the Hedwig client.  

For more information on setting up Sentry in the Hedwig client source see:
* https://sentry.io/skylight-digital/hedwig-fe-staging/getting-started/javascript-react/

The change to source code to support Sentry in the Hedwig Client must not be executed in the docker-based run-times used for local development and PR systems.

Once the client source has been modified to support Sentry, the Hedwig Release pipelines need to be updated to embed Sentry environment (e.g. Staging, UAT, Production) data in the client source.  Updating the Release pipelines will be tracked in another issue .

**Comment by jlhogan** [comment]
will the env-specific `DSN` be injected in pipeline?

**Comment by speedcm** [comment]
The Hedwig Release piplines will be updated with a task to embed the "DSN" & "Release" data into the specified file.  If the file is not a json file, then we use tokens to update the values.  See the web.config file (see ecis-experimental\installer\iis\web.config) for token syntax.  

Here is some information on how to embed the "Dsn" and "Release", 
* https://developer.bring.com/blog/sentry-usage-in-react-application/

We do not implements Tags or Environments.

**Comment by speedcm** [comment]
We currently setup variables in the pipeline called Sentry.Dsn and Sentry.Release.  If we use tokens can we use these values, __Sentry.Dsn__ & __Sentry.Release__ ?

**Comment by jlhogan** [comment]
ah great! will update the PR accordingly. thanks !

**Comment by speedcm** [comment]
I can test in the UAT environment so we do not disrupt Staging.  Do you think we should be in a dummy exception to validate it is working?

**Comment by speedcm** [comment]
FYI in the backend, if the Sentry.Dsn value is not specified in the appsettings file, Sentry is not invoked during backend execution.  I am not sure how this behavior is implemented in the frontend.  Worst case we might want to disable Sentry is something weird is happening with it.
