### ISSUE TITLE
Redesign the landing page to include information about the tool and links to OEC resources

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#763]
**Story:** When using ECE Reporter, I want to see a landing page with context about how to log in, how to access the privacy policy and where I can go for more information if I have questions.

**Additional context:** This ticket creates a new landing page that providers access via the root URL, and which links to the current identityserver login page. The page has three main sections: a hero image banner with a sign-in link, information about ECE Reporter (including a link to the OEC privacy policy), and a link to the OEC website. The placement for these sections can be found in the InVision prototype/screenshot shown at the bottom.

**Related:** https://github.com/ctoec/ecis-experimental/issues/878 (logout landing page)

**Acceptance Criteria:**
- The hero image at the top includes the following copy:
  > Welcome to ECE Reporter. 
  > Please sign in.
- This section also includes a `Sign in` button, which links to the existing identityserver login page.
- The middle section includes the following body text:
- Title 
  > Supporting affordable child care in Connecticut
- Body  
  >  Publicly-funded early care and education programs use ECE Reporter to share data with the Connecticut Office of Early Childhood. We use this data to pay programs and help families access quality care.
- Include a link to the Privacy Policy in this section, labeled "Read the Privacy Policy", along with an [icon](https://fontawesome.com/icons/chalkboard-teacher?style=solid)
- Include an [image](https://www.dropbox.com/sh/x93vkig8t87w08f/AAB-_nlom8J32Mhfm47cUz8ga/ER3A9272.jpg?dl=0) in this section.
- The third section has the text "Find out what's new at OEC", with a button linking to the OEC website (http://stage.ctoec.org/) labeled "Visit the OEC website" 
**Design:**
[Invision Prototype](https://skylight.invisionapp.com/console/Hedwig%20v2-ck3osnej20a5g019gndj3g45z/ck729we5c007a011er7fwl8p6/play)

![image](https://user-images.githubusercontent.com/30734760/76772862-93fbb980-676f-11ea-8e9d-840c1f0cab46.png)

**Comment by abbyraskin** [comment]
Is this the final design?

**Comment by cmgiven** [comment]
@atreni Can we revert to what we reviewed on Friday? I don't think this more involved design is quite there yet. Happy to think through it together during design sync or 1:1 if useful, but also know focus is elsewhere, so eager to keep this minimal.

**Comment by cailyncodes** [comment]
Perhaps not too important atm but is this to replace the IdentityServer/WingedKeys page or are we trying to add this to Hedwig?

**Comment by cmgiven** [comment]
The thought is to add to Hedwig, replacing the blank home page and separate log in flow, ideally. You know best though, any thoughts on the lift to bring this into the app? Or security reasons to keep it separate?

**Comment by cailyncodes** [comment]
Probably a higher-side medium LOE. We have to be able to make a POST request to wingedkeys but it probably requires that the Host/Origin matches the wingedkeys URL. So I think we'd have to update WingedKeys to add a new route that we can hit with a POST and then backend issue a POST to the authenticate endpoint, carrying the credentials in the body. We shouldn't transmit credentials over GET (URL string or HTTP Header) as much as that would make this process easier

**Comment by abbyraskin** [comment]
From storytime: designs are in progress - plan is to navigate from sign in button to identity server, and add a logout state.

**Comment by abbyraskin** [comment]
Copy here: https://docs.google.com/document/d/1rP67X-_WWt9DACBpKDPF19mTYdbcJN7et-m0CxIJWsc/edit?usp=sharing

**Comment by abbyraskin** [comment]
I have a couple open design questions, which I added comments about in the prototype. Will look for dev input on whether it makes sense to break out the copy changes on logout (we've built the redirect already, but the copy on this page changes slightly after logging out).
