### ISSUE TITLE
refactor forms to use form reducer

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#768]
Form reducer exists in code, but so far is only used in https://github.com/ctoec/ecis-experimental/blob/master/src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx

update other forms to leverage this instead of endless state vars

- [x] childInfo
- [x] familyInfo
- [x] familyIncome
- [x] withdraw ?
- [x] report submit ?

**Comment by cailyncodes** [comment]
Closed by #835
