### ISSUE TITLE
organizations/{orgId}/enrollments grows exponentially

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#777]
Each `Enrollment` on this endpoint contains a `Site`. Each `Site` contains an array of complete `Enrollment` objects, with the exception of the root `Enrollment`. This is exponentially increasing the size of the response, and leading to >70MB responses for our largest site (235 enrollments being sent as a total of 55,225 enrollment objects).

**How to reproduce:** Load the roster page, and examine the Enrollments xhr.

**Expected behavior:** The json returned by the server does not contain nested enrollments under Site.

**Comment by jlhogan** [comment]
perhaps lazy loading (https://docs.microsoft.com/en-us/aspnet/web-api/overview/data/using-web-api-with-entity-framework/part-4#lazy-loading) plus DTOs (https://docs.microsoft.com/en-us/aspnet/web-api/overview/data/using-web-api-with-entity-framework/part-5) could solve this problem? 

May also give us a layer at which we can easily enforce read-only rules

**Comment by cmgiven** [comment]
Yup. DTOs might be the most direct approach. It feels like a lot more overhead, but explicit and less error-prone.

The other option I found is to define a custom JSON.net ContractResolver that knows to ignore nested attributes. We could for example create one that says "I will only resolve a given class at one level of a tree, so if I have an Enrollment nested somewhere inside an Enrollment, I will ignore it." This goes beyond the basic "ignore" rule we have in the configuration, which only prevents looping of the same instance, which is why each enrollment has N-1 enrollments nested within it; JSON.net is dropping the one that is the grandparent.

**Comment by jlhogan** [comment]
Guess that depends on how we feels about the read-only solution i have up in PR right now. If it feels pretty good, may be simplest to define the resolution rules and leave it at that.

if others think it's still pretty hack-y /confusing/error prone, then maybe we go with DTOs. Shouldn't be too bad to create these defns and mark the internal models as such.

**Comment by cailyncodes** [comment]
I think I'm slightly leaning more to a DTO -- I think it would be relatively low lift (and we could consider using a library like https://automapper.org/ to make it even easier). I feel that the read-only solution is a good stop gap but should be shored up with a more stable approach

**Comment by jlhogan** [comment]
that's my inclination as well. My thoughts on using automapper are mixed after reading some reddit threads (lol...) but that can be discussed separately from a DTO/no-DTO decision.
