### ISSUE TITLE
Immutable data schema

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#8]
**Story:** As an OEC data analyst, I want to be able to see the data as it existed at some point in the past, and I want to know who changed the data and when.

**Acceptance criteria:**

* Attributes of the following entites are immutable, that is they are updated not by overwriting the existing values but by inserting new values.
  * `Child`
    * Attributes that are permanent: `Id`
    * Attributes that can be updated: Everything else, including the foreign key `FamilyId`
  * `Family`
    * Attributes that are permanent: `Id`
    * Attributes that can be updated: Everything else (there's not currently anything else in the schema, but two that will likely be added: address and Care 4 Kids Family ID
  * `FamilyDetermination`
    * Attributes that are permanent: `Id`, `FamilyId`
    * Attributes that can be updated: Everything else
  * `Enrollment`
    * Attributes that are permanent: `Id`, `ChildId`, `SiteId`
    * Attributes that can be updated: `Entry`, `Exit`
  * `Funding`
    * Attributes that are permanent: `Id`, `EnrollmentId`, `Source`
    * Attributes that can be updated: `Entry`, `Exit`
* We possibly want to write a tech spec for this one, but some rough implementation thoughts follow.
* Each of these entities is split into two tables/models. One contains all of the permanent attributes. The other, possibly named something like `ChildMutableAttributes` contains the attributes that can be updated.
  * There is a one-to-many relationship between the permanent table and the mutable table.
  * Each record in the mutable table contains a modification timestamp, the user who made the modification, whether the record has been deleted, and a column like `SupersededBy`.
  * When an entity is to be updated, a new record in the mutable table is created. The Id of this new record is written to the old record as `SupersededBy`. Therefore, to retrieve the most recent record, one need only look for the records where `SupersededBy` is null.
  * All data should be copied to the new mutable record, not just the data that was updated.
* This immutable schema should be abstracted for the end user. Indeed, we should ideally not have to split even the repositories into multiple classes. Instead, each repository fetches the most recent mutable record (the ones for which `SupersededBy` is null). Using `Include`, it prefetches the permanent record as well. API consumers don't need to know whether a given attribute comes from the permanent record or a mutable one. The repository handles inserting updates correctly, and the API always uses the Id of the permanent record, such that for an API consumer, there is no difference to what they would expect from a standard mutable schema.

**Related:** #7

**Comment by jlhogan** [comment]
system-versioned temporal tables: https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-2017

intended for use cases that are more time-specific (temporal table, after all) but is a transparent implementation of a completely maintained historical record of data rows over time. All modifying DML results in old data being written to a history table before current table is updated. Could meet our needs, altho I'm not sure how graphQL/apollo will play.

**Comment by cmgiven** [comment]
This seems pretty cool. Having the database handle this would be awesome.

Maybe you're already thinking along these lines, but here's an interesting test case to think through how the API surfaces historical data, which'll be more fully described in #15 when I write up the AC. In short, when we display a submitted report, we'll need to be able to look at the data as it existed at the time the report was submitted. Based on reading that doc, it looks like I could just add `AS OF` to my query with the timestamp of when the report was submitted. (Which again, super nifty.) How would we expose that through GraphQL?

**Comment by jlhogan** [comment]
seems it is possible to build out query functions for AS OF: https://www.eidias.com/blog/2018/8/29/using-sql-temporal-tables-with-entity-framework-core
then build queries to hook up graphql schemas to the custom repository functionality for temporal querying. 

Right now, temporal tables are not supported by EF natively, but seems that this will happen _eventually_ (https://github.com/aspnet/EntityFrameworkCore/issues/4693 is marked as "consider for next release"). I don't feel like any of these "work arounds" are particularly hacky, except maybe the raw SQL we'll have to write. But as that blog points out, we can wrap all this in extension methods so it only needs to exist in one place.
