### ISSUE TITLE
Remove site dropdown in EnrollmentFunding section

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#809]
**AC**:
- Site input + dropdown should be replaced by static informational text with the site name. specifics are implementers choice ;)

**Comment by cailyncodes** [comment]
I can repro. Also this errors happens when editing to a new site:
![FundingSiteChangeEdit](https://user-images.githubusercontent.com/16420449/75473299-e14fec80-5962-11ea-956e-51bc6982087d.PNG)
