### ISSUE TITLE
Only private pay when no age group selected

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#810]
If Age group is not selected, only private pay will be an option in funding dropdown.

**Comment by cailyncodes** [comment]
@abbyraskin @atreni Do we consider this a bug?

**Comment by mmazanec22** [comment]
Maybe we could always display all options but have the unavailable ones disabled until age group is selected?

**Comment by abbyraskin** [comment]
It looks like this was already resolved.
