### ISSUE TITLE
Storybook in staging

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#819]
Can we run & expose storybook in the client in staging environment

**Comment by cailyncodes** [comment]
@speedcm Is there anything you need to do to terraform to support port 9009 being open?

**Comment by cailyncodes** [comment]
@jlhogan @speedcm I also think we would need to be able to run node directly on the windows instance. If I am not mistaken, we currently bundle the app and run it behind IIS? I'm not sure this is an easy lift. Perhaps it is better to spin up a separate storybook EC2 instance with node installed

**Comment by speedcm** [comment]
@belucid 
To open up port 9009 in the VPC we need to update Terraform to:
  * create a security group for storybook for 9009
  * apply the security group to the beanstalk system

**Comment by speedcm** [comment]
The EC2 system we are using for Beanstalk is a windows system running IIS. The Beanstalk system does not have nodejs installed.  What are the options for deploying this storybook artifact?  Are we allow to deploy a container?

**Comment by cailyncodes** [comment]
We could deploy this as a Windows Docker container. We could whip up a quick Docker file, package it in site.zip, build the container on EC2, and then run it with Docker.

**Comment by speedcm** [comment]
I need to check with @belucid about security for this.  I am thinking that we do the following:
  * Update Build Pipeline (update azure-pipeline.yml) as follows:
    * Produce a docker image via docker build
    * Create a new artifact with a) docker image and b) docker compose file
  * Update Staging Release Pipeline as follows:
    * Run pre-install script 
      * Stop docker processes
        * docker stop $(docker ps -a -q)
      * Remove docker containers
         * docker rm $(docker ps -a -q)
      * Remove docker images
         * docker rmi $(docker images -q)
     * Stage docker files
       * Copy docker image to docker engine storage location
       * Copy docker compose file to EC2 system
     * Startup docker
        * docker-compose up -d

I would like to prototype this manually first to make sure it works.  Then, I would
  * Update Terraform to create the EC2 for staging
  * Update the Staging Pipeline

This will only be implemented for staging.  To implement this, I would like to use UAT. 

This approach needs to be approved by Sean before we proceed. 

Just my thoughts.

**Comment by speedcm** [comment]
Another simpler option maybe to:
  * Setup EC2 system with:
     * WebServer (e.g. Apache, Nginx)
  * Update Build Pipeline (update azure-pipeline.yml) as follows:
     * Export the storybook during the build 
        * https://storybook.js.org/docs/basics/exporting-storybook/
     * Create zip archive for directory structure
     * Create new artifact for zip archive
   * Update Staging Release Pipeline as follows:
     * Copy zip to EC2 system
     * Overwrite directory structure on EC2 system
   * Restart webserver (nginx, apache)

**Comment by speedcm** [comment]
We implemented the simpler option specified in this issue.  The PR for this was merged into master on 03/16/20.  

  * See https://github.com/ctoec/ecis-experimental/pull/860

The staging pipeline will be updated to deploy storybook after hours to ensure there is no disruption to the CI/CD process during normal working hours.

**Comment by speedcm** [comment]
The staging release pipeline has been updated to deploy storybook. Staging storybook is accessible via http://staging.oec-component-library.ctoecskylight.com/
