### ISSUE TITLE
Migrate db via application - remove need for jumpserver db deployments

### ISSUE THREAD

**Issue by speedcm** [ctoec/ecis-experimental#833]
The hedwig Release Pipeline deploys the hedwig database first to RDS, then the hedwig application is loaded into Elastic Beanstalk.  

Deploying the database to RDS via the Release Pipeline requires the following:
  * A task to copy the SQL script to the Jump Server
  * A task to execute the SQL script on the Jump Server against the target hedwig database

The goal of this issue is to a) remove the need for a Jump Server to deploy the hedwig database, and b) deploy the hedwig db via the application (executing in Elastic Beanstalk).

**Comment by speedcm** [comment]
Approaches
  * https://stackoverflow.com/questions/38852328/run-custom-sql-script-on-app-start

**Comment by cmgiven** [comment]
@speedcm Is this done? Should we close?

**Comment by speedcm** [comment]
This issue is still open.  I have done analysis on possible solutions.  However, I will need some development support/assistance to implement this issue.
