### ISSUE TITLE
Validate that a child is not claimed on the same report twice

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#852]
As a provider, if I have a child who moves from an Infant/Toddler program to a Preschool program, I can not claim them for both slots during the same reporting period.

**AC:**
* A Funding is invalid if it overlaps with another Funding (its LastReportingPeriod is the same or greater than the FirstReportingPeriod of another Funding) for the same Child and same Funding Source.
* A report with an overlapping funding cannot be submitted.
* The latter of two overlapping fundings should show a validation error on the First reporting period field with the message "Cannot claim a child twice in a reporting period."
* The First Reporting Period dropdown menu should not show any ReportingPeriod used by a previous funding, unless that reporting period is already selected (thus showing the validation error).

**Comment by abbyraskin** [comment]
@cmgiven do you remember the context here? is this something to prioritize in the near term?

**Comment by cmgiven** [comment]
As a provider, if I have a child who moves from an Infant/Toddler program to a Preschool program, I can not claim them for both slots during the same reporting period.
