### ISSUE TITLE
Fundings are associated with FundingSpaces (part-time/full-time splits)

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#858]
**Ticket 1 of 2**

**User story:** As a provider, I want to enroll a child in a space that might be full-time, part-time, some combination thereof, or even not providing services some weeks of the year.

**Background:** Currently, our schema assumes that a child's funding corresponds to either 52 weeks of full-time care, or 52 weeks of part-time care. We indicate the FundingTime on the Funding, either full- or part-time. We use this to match a given child's funding to a FundingSpace, each of which has a FundingTime, for example, when we calculate the utilization on the Roster legend or on a ReportDetail.

But this is a simplification. In fact, a FundingSpace could have some mix of full-time weeks, part-time weeks, or weeks when services were not provided. And a Funding would not be part- or full-time, but rather associated with a FundingSpace.

There are effectively infinite combinations of part- and full-time making up FundingSpaces. You might have 38 weeks of part-time and 14-weeks of full time. You might have 40 weeks of part-time and 12 weeks of full-time. You might have 40 weeks of full-time (and 12 weeks of no services provided).

This ticket describes a refactor and schema change to create a direct association between a Funding and a FundingSpace, and to store the FundingTime exclusively on the funding space. The existing data should be migrated to the new format. It does not yet implement any features related to part-time/full-time split spaces; the only spaces will be 52 weeks of part-time or 52 weeks of full-time, and the user experience should be unchanged.

**AC:**

* Fundings have a many-to-one relationship to a FundingSpace.
* Fundings no longer have a FundingTime. However, the FundingTime must be used to identify which FundingSpace existing Fundings correspond to (along with the AgeGroup and Site from the Enrollment).
* Existing data can be migrated into this new schema.
* The Roster continues to work as expected, using the FundingTime from the associated FundingSpace instead of an attribute on the Funding model.
    * There is an opportunity to refactor the Roster legends to take advantage of this new association.
* The Enrollment and Funding section continues to work as expected, with the drop-down menu for Funding populated with available FundingSpaces for the Organization and AgeGroup.
* The ReportDetail continues to work as expected.

See #876 for part 2.

**Comment by jlhogan** [comment]
https://github.com/ctoec/ecis-experimental/pull/916 part 1 of part 1, add fundingSpaceId to funding. Tested migration against copy of prod data, validated results:

```
1> select count(*) from funding where fundingspaceid = null                     
2> go                                                                           
                                                                                
-----------                                                                     
          0                                                                     
                                                                                
(1 rows affected)                                                               
1> select f.time, fs.time, e.agegroup, fs.agegroup, s.organizationid, fs.organizationid                       
2> from funding f                                                                                             
3> join enrollment e on f.enrollmentid = e.id                                                                 
4> join site s on e.siteid = s.id                                                                             
5> join fundingspace fs on fs.id = f.fundingspaceid                                                           
6> where (                                                                                                    
7> f.time != fs.time                                                                                          
8> OR e.agegroup != fs.agegroup                                                                               
9> OR s.organizationid != fs.organizationid                                                                   
10> )                                                                                                         
11> go                                                                                                        
time        time        agegroup    agegroup    organizationid organizationid                                 
----------- ----------- ----------- ----------- -------------- --------------                                 
                                                                                                              
(0 rows affected)                                                                                             
```
