### ISSUE TITLE
Change "Jackie" username to "Jacki"

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#862]
Change the spelling of Jacki Gillian's username, a pilot user from Southfield Children's Center, should be to jacki.gillian (remove the "e" in the first name).

**Comment by cailyncodes** [comment]
@abbyraskin Can you check and confirm that this issue is resolved?

**Comment by jlhogan** [comment]
@cailyncodes  confirmed in prod, this is resolved!
