### ISSUE TITLE
remove duplicate information in WIthdrawal page

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#872]
**AC**:
- Funding tag without time is first line in right column (vs comp below where time abbrev is included)
- `Enrollment: [pretty formatted time]` is next line in right column (vs comp below where it displays raw time, not formatted)
- fix alignment of enrollment end date label and input (should be stacked)
- Snapshot tests added for Withdrawal page

![pasted image 0](https://user-images.githubusercontent.com/54035880/76766646-b17c5380-676e-11ea-977e-4df0f87f8d02.png)

design decision: https://docs.google.com/document/d/1G5_yfnFxo8XjtEZlC_GLJ0Suq9iQUPx7rM302py1Akg/edit?disco=AAAAJLfyHiU

**Comment by mmazanec22** [comment]
Currently there is neither a tag nor text indicating enrollment time?

**Comment by jlhogan** [comment]
I believe there was a regression in the withdrawal refactor https://github.com/ctoec/ecis-experimental/blob/2e55a1aa3101b7cdde830ac4a4b86e74913848e9/src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx#L207

see invision prototype for desired state:https://skylight.invisionapp.com/public/share/FZWU9IO32#/screens/390270034

![Screenshot from 2020-03-27 16-54-46](https://user-images.githubusercontent.com/54035880/77799695-b339f700-704b-11ea-84e4-aba555460046.png)

the duplication was that the funding type tag includes the time abbreviation, and then the second line where it says `Enrollment: Full Time` is redundant. AC in the ticket has been updated to reintroduce funding tag, but without time, and enrollment time text, and to add a snapshot test to capture this. 

note: The ability to optionally create funding tag without `time` will be relevant here https://github.com/ctoec/ecis-experimental/projects/1
