### ISSUE TITLE
Logout landing page

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#878]
**Story:** As a provider, when I log out of ECE Reporter, I'm taken to a landing page that gives me feedback that I've logged out.

**Related ticket:** [#763 - landing page redesign](https://github.com/ctoec/ecis-experimental/issues/763)

**Acceptance Criteria:**
- When a user logs out, they are redirected to a slightly modified landing page. The button label changes to `Sign back in`, and the hero copy states the following:
  > "You’ve been logged out. Thank you for using ECE Reporter!" 

**Design:** 
Note: the copy in the top section changes, per AC above:
![image](https://user-images.githubusercontent.com/30734760/76779949-31f48180-677a-11ea-8e1c-bdadc1a05aaf.png)

**Comment by julyytran** [comment]
Decided not to do this since there is (unstyled) logout feedback and there will be redirect to login when timing out
