### ISSUE TITLE
UI style/spacing/copy changes

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#884]
components:
- internal lines (between dropdown options) match the row separator lines in table component
- ~common container backTo links have more top spacing~ (Resolved by #897)

report:
- standardize width of Other Revenue input boxes
- use ReportingPeriodFormatter formatted dates for report sub-header (currently, date range is manually formatted)

roster: 
-  ~update sub-header language for single-site roster view of multi-site org
current is misleading, b/c the site-specific X/30 does not accurately represent org-wide utilization. Instead, only use the "ratio" style in single-site org or unfiltered multi-site org view. In filtered single-site, update subheaders to:~
```
X in full time CDC space(s)
```
covered by #893

**Comment by mmazanec22** [comment]
Adding to this list: fix family fees missing info error spacing in report submit form
