### ISSUE TITLE
update overutilization alert display logic

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#887]
**User story**: as a user, I expect to see an overutilization alert when creating/editing an enrollment funding only when a first reporting period has been selected

**AC**:
- overutilization alert is not display if no first reporting period selection

**questions**:
- Should we expand this to check for overutilization in all reporting periods? (currently only checks current reporting period, and assumes child is being added to current reporting period but this can frequently not be the case)
- Should correct utilization be enforced by the API? Or should we continue to allow users to overutilize?

**Comment by julyytran** [comment]
Moving to design board to consider in the context of handling overutilization in all flows
