### ISSUE TITLE
Legends use FundingSpaces consistently

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#893]
**Prerequisites:** #858, #876

**User story:** As a provider, I use the legends to understand whether each of my slots is fully utilized so that I can identify whether I need to enroll or withdraw a child, and I expect the legends to accord with each other on the same page, or between my program and the individual sites.

_This ticket updates the legends to use schema changes introduced by the prerequisite tickets, but also documents how the legends should appear under a variety of states that have fallen out of consistency with each other._

**Terms:**

Program roster: The roster for the organization. If the organization is a single-site organization, tis is the only roster that will appear.
Site roster: The roster for a specific site.
Global legend: the legend that appears at the top of the page.
Age group legend: the sub-legend that appears above each age group.

**AC:**

* **Base case:** The program roster, with a single date selected as the date range.
  * **Global legend:**
    * For each unique FundingSource among an organization's FundingSpaces (currently just CDC), a legend item appears in the format: "[CDC tag] [spaces used]/[spaces available] CDC spaces filled"
      * Spaces used sums across all children who have a funding of the given FundingSource that was active within the date range being shown by the roster, regardless of age group.
      * Spaces available sums all FundingSpaces of the given FundingSource, regardless of age group
      * Even when there are no spaces used, the legend item should appear, as long as the organization has a FundingSpace of the given FundingSource.
    * The C4K and missing information legend items count all kids who had an enrollment active within the date range being shown on the roster.
      * When there are no kids receiving C4K funding or missing information, these legend items should be hidden.
  * **Age group legend**
    * The age group headers should be shown if there is a FundingSpace or if there is any child enrolled in the age group. They should only be hidden if there is no FundingSpace AND no children enrolled.
    * There is one legend item per FundingSpace of a given age group.
    * Even when there are no spaces used, the legend item should appear.
    * Use "Part time / full time" when a FundingSpace includes a mix of part- and full-time weeks.
    * The "part time" "full time" labels should appear even when there is only a single FundingSpace in a given age group. C.f. #892, which hides those labels from the tags on individual children because they will be shown here.
* **When the roster's date range spans multiple days.**
  * All legend items should no longer show spaces available (i.e. "24 spaces filled" instead of "24/24 spaces filled").
* **Site roster.**
  * Like when the roster spans multiple days, all legend items should no longer show spaces available (i.e. "24 spaces filled" instead of "24/24 spaces filled").
  * Additionally, when a legend item has no spaces used, it should be hidden. When an age group has no children, it should be hidden. Note that this differs from the program roster, where we show any legend item or age group that has a corresponding FundingSpace, even when empty.

## Program roster

<img width="696" alt="Screen Shot 2020-04-02 at 1 36 18 PM" src="https://user-images.githubusercontent.com/5375557/78290300-2a0e3e80-74e9-11ea-849d-a3f86e403e81.png">

## Site roster

<img width="699" alt="Screen Shot 2020-04-02 at 1 36 23 PM" src="https://user-images.githubusercontent.com/5375557/78290314-31354c80-74e9-11ea-8a30-a4d91bbbdc87.png">

**Comment by mmazanec22** [comment]
Closed by #968
