### ISSUE TITLE
Funding interface selects from available funding spaces

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#894]
**Prerequisites:** #858, #876, #890 

**User story:** As a provider, I want to enroll kids in funding spaces as described in my contract. If I only have one kind of funding space for an age group, I shouldn't need to select it.

**AC:**

* Replace the dropdown menu with an interface as shown in the designs (component implemented by #890).
* Initially, the "Private pay" option is selected. Choosing "Child Day Care" reveals options to select a Contract space (showing the available FundingSpaces for the organization and age group) and a First funding period.
* If I only have one FundingSpace for the organization and age group, the dropdown menu is replaced by text indicating the type of space.
* Validations of the First funding period are the same as existing behavior.
* Validations require a FundingSpace is selected
* Validations prevent a user from associating a funding with a fundingspace that:
    * is not owned by the same organization that owns the funding enrollment site (fundingspace.organizationId == funding.enrollment.site.organizationId)
    * does not have the same agegroup as the funding enrollment (fundingspace.ageGroup == funding.enrollment.ageGroup)

## When there are multiple FundingSpaces

<img width="243" alt="Screen Shot 2020-03-19 at 10 21 42 AM" src="https://user-images.githubusercontent.com/5375557/77083414-775bbd80-69cb-11ea-94cc-0bfcd9dcdef4.png">

## When there is only one FundingSpace for the organization and age group

<img width="264" alt="Screen Shot 2020-03-19 at 10 21 46 AM" src="https://user-images.githubusercontent.com/5375557/77083423-7aef4480-69cb-11ea-8dc6-75bb54b72b34.png">

## Expanded dropdown with examples of formatting

<img width="223" alt="Screen Shot 2020-03-19 at 10 21 50 AM" src="https://user-images.githubusercontent.com/5375557/77083429-7dea3500-69cb-11ea-8d05-cfcff122c98b.png">

**Comment by jlhogan** [comment]
What should the summary view look like RE funding times?

**Comment by cmgiven** [comment]
Let's use strings like this:

> CDC — Full time (52 weeks)

So the abbreviated funding source, an em dash, followed by the FundingSpace as it would appear in the dropdown menu.
