### ISSUE TITLE
Report records part-time/full-time weeks

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#895]
**Prerequisites:** #858, #876 

**User story:** As a provider, I want to inform OEC when I've used one of my full-time weeks so they will reconcile my funding appropriately.

**AC:**

* When one of an organization's FundingSpaces are split between part-time and full-time, an additional question will appear on the report above the utilization table. If multiple FundingSpaces are split, a question will appear for each.
* Splits that do not add up to 52 weeks are currently not supported. If the report encounters this case, it should throw an exception.
* The title of the new question is "[Age] services were provided [Time]", where Age is the age group of the FundingSpace, and Time is either "full time" or "part time".
    * We use the less common Time for the question. So if a space has 40 weeks of part-time care and 12 weeks of full-time care, the question would use "full time". If the space has 44 weeks of full-time care and 8 weeks of part-time care, we would use "part time." If the weeks are evenly split, default to asking about "full time".
* The question uses a small text input to construct a sentence of the format "[0] of [X] weeks in [Month]. See designs. (Note that weeks remaining is added by #901, and the utilization table is updated by #896.)
* The text input should only accept whole numbers between 0 and the number of weeks in the reporting period.
* The answer should be saved with the report. Although we've only asked about either part-time or full-time, because all splits add up to 52 weeks, we know and should record both, i.e. 1 week of full-time and 4 weeks of part-time.
    * For consistency, we probably also want to record the number of weeks of part- or full-time for the spaces we didn't ask about.
* The data should be updated on defocus, so that the changes are reflected in the utilization table (#896).

## Design

<img width="801" alt="Screen Shot 2020-03-19 at 1 11 28 PM" src="https://user-images.githubusercontent.com/5375557/77103713-d7149180-69e8-11ea-9557-7cb6a5bf00eb.png">

**Comment by jlhogan** [comment]
waiting on refactor of FundingSpaceAllocation to table reference (vs. current impl as json blob)
