### ISSUE TITLE
Utilization table calculates and displays part-time/full-time weeks

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#896]
**Note**: branch off work here https://github.com/ctoec/ecis-experimental/pull/1020 ( includes https://github.com/ctoec/ecis-experimental/tree/895-new and https://github.com/ctoec/ecis-experimental/tree/895-reports-record-funding-weeks) if you begin this work before PR is merged 

**Prerequisites:** #891 (maybe; they're closely related), #895, #938 

**User story:** As a provider, I want to see an accurate accounting of what I have been paid by OEC on my monthly reports, even when I am claiming a mix of part- and full-time weeks.

**AC:**

* The row header (the leftmost column) should only show "part time" or "full time" when there are multiple FundingSpaces for an age group.
    * If there are multiple FundingSpaces for an age group, and one of the FundingSpaces has a mix of part- and full-time weeks, it should show as "pt/ft split".
* Using the information recorded by #895, some rows may have a combination of part- and full-time weeks, and thus two different rates. We display this by showing two lines in the "Reimbursement rate" column (see design).
    * When all of the weeks are either part- or full-time, we don't need to show a line with "0 weeks". We only show the week/rate combinations that are in use.
* The total and balance columns remain a single line, and sum the products of the part- and full-time weeks.
* Utilization table is updated to correctly handle multiple sites for an organization

## Design

<img width="801" alt="Screen Shot 2020-03-19 at 1 11 28 PM" src="https://user-images.githubusercontent.com/5375557/77100149-29eb4a80-69e3-11ea-94af-f0d2d4489058.png">

**Comment by mmazanec22** [comment]
Closed by #1115
