### ISSUE TITLE
Roster has "Date modified" column

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#9]
**Story:** As a provider, I want to see the date I last modified an enrollment record so that I can identify records where the data may be out-of-date.

**Acceptance criteria:**

* My roster has a column called "Date modified".
* This column is sortable.
* The date in this column is the most recent modified date from any of the following: `Child`, `Family`, `FamilyDetermination`, `Enrollment`, `Funding`.

**Dependencies:** #8

**Comment by abbyraskin** [comment]
This is moot (we decided not to include this column) - closing.
