### ISSUE TITLE
Pipeline Build - SonarCloud Analysis - TypeScript 2.9.2 not supported

### ISSUE THREAD

**Issue by speedcm** [ctoec/ecis-experimental#90]
In the Azure DevOps 2019 Pipeline build we get the error below.  SonarCloud errors do not cause the build to fail.  As a result, the build is successful.
---
ERROR: Failed to analyze file [ClientApp/src/containers/Enroll/Enroll.tsx]: You are using version of TypeScript 2.9.2 which is not supported; supported versions >=3.2.1
ERROR: Failure during analysis, Node.js command to start eslint-bridge was: {NODE_PATH=/home/vsts/work/1/s/src/Hedwig/ClientApp/node_modules/uswds/node_modules} node /home/vsts/work/1/.sonarqube/out/.sonar/.sonartmp/eslint-bridge-bundle/node_modules/eslint-bridge/bin/server 34907
java.lang.IllegalStateException: Unsupported TypeScript version

**Comment by cmgiven** [comment]
Strange, we're on 3.6.3.

**Comment by speedcm** [comment]
Looks like Hedwig has a transitive dependency to typescript 2.9.2 via direct dependency to uswds 2.1.0

1. Hedwig direct dependencies are specified here:
https://github.com/ctoec/ecis-experimental/blob/master/src/Hedwig/ClientApp/package.json

2. Hedwig has a dependency to usdw:
...
"uswds": "^2.1.0",
...

3. Here is the source code for uswds version 2.1.0
https://github.com/uswds/uswds/archive/v2.1.0.zip

4. uswds has a direct dependency to typescript 2.9.2
    "typescript": {
      "version": "2.9.2",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-2.9.2.tgz",
      "integrity": "sha512-Gr4p6nFNaoufRIY4NMdpQRNmgxVIGMs4Fcu/ujdYk3nAZqk7supzBE9idmvfZIlH/Cuj//dvi+019qEue9lV0w=="
    },

5. Current version of uswds is 2.2.1
This version also has a dependency to typescript 2.9.2

**Comment by cmgiven** [comment]
SonarCloud should probably be ignoring anything in node_modules, yes?

**Comment by cmgiven** [comment]
(We're not using any of the uswds Javascript, so there's not a `require` or anything that would require loading uswds type definitions.

**Comment by speedcm** [comment]
Sonar introduced this bug/feature 2 days ago:  
- https://community.sonarsource.com/t/you-are-using-version-of-typescript-3-1-6-which-is-not-supported-supported-versions-3-2-1/15232

Sonar bumped up the version requirements:
- https://github.com/SonarSource/SonarJS/commit/42841cf46140cdbdaba8c83fc1bbe8b1e1ab1640

**Comment by speedcm** [comment]
This issue is now resolved.  To resolve this issue, the following was done:
* azure-pipelines.yml was update as follows:  
  * sql script generation (dotnet ef --verbose migrations) moved under dot net publish
  * included script (npm install typescript --loglevel verbose) just before sonarcloud analyze
