### ISSUE TITLE
Filtered roster from report update alert

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#902]
**User Story**: As a user, when I navigate back to the roster from an un-submittable report to update missing information, I am shown a filtered roster containing only the enrollments blocking my report submission

**AC**:
- roster can be filtered by date in multi-site view
- roster can be filtered by missing information 
- roster can be filtered by funding
- roster filters are persisted via URL params, so after editing an enrollment, the user returns to the filtered roster view
- for now, new roster filters (missing info, funding type) cannot be applied by a user from the roster view, but rather can only be applied via url params

**Comment by abbyraskin** [comment]
Note from storytime: identify which elements in roster will be hidden, and any necessary copy changes.

**Comment by abbyraskin** [comment]
I think we're scrapping this in favor of roster preview - will confirm with team today.

**Comment by abbyraskin** [comment]
Closing in favor of future work that will take priority.
