### ISSUE TITLE
Return user to incomplete enrollment if they navigate to Withdrawal

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#912]
What should it say, error or info, etc

**Comment by jlhogan** [comment]
I believe this is another regression from the withdrawal refactor. See: https://github.com/ctoec/ecis-experimental/blob/dbda5342cde6dd6adc7f9469bf686073546962b1/src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx#L132

The withdrawal page should automatically redirect the user back to the enrollment detail view for the incomplete enrollment, and display the `missingInformationForWithdrawalAlert`
