### ISSUE TITLE
Truncate site column to prevent breaking to multiple lines

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#926]
**User story:** As a multi-site organization, I typically have lots of kids on my roster. If the site column breaks to multiple columns, my roster becomes huge and difficult to scroll through, and printing consumes extra pages of paper. Instead, I want to ensure that each kid only takes a single row.

**AC:** Truncate the "Site" column on the roster to ensure that it always fits on a single line. If not all characters of a site are visible, use an ellipsis (…) to indicate that fact.

**Comment by cailyncodes** [comment]
white-space: nowrap;

overflow: hidden;

text-overflow: ellipsis;

max-width: min-content;
