### ISSUE TITLE
dateInput component needs styling for warning/error inside warning/error fieldSet (i.e. input box gets colored outline)

### ISSUE THREAD

**Issue by julyytran** [ctoec/ecis-experimental#931]

**Comment by julyytran** [comment]
Seems to not be an issue anymore

**Comment by jlhogan** [comment]
it's still an issue. See date of birth input box compared to birth certificate:
![Screenshot from 2020-05-14 14-24-30](https://user-images.githubusercontent.com/54035880/81971173-ac147b80-95ee-11ea-91f0-9f242f3dd779.png)

not a big deal, but an inconsistency.

**Comment by julyytran** [comment]
Ah ok, thank you. Reopening.
