### ISSUE TITLE
Report detail view broken

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#938]
**To be addressed by:** #939 

https://github.com/ctoec/ecis-experimental/pull/932  uncovered a bug in the transform entity filter:

`CdcReport.Organization.Reports` does not get set to null because Reports is a reference to a collection of `OrganizationReport`s, which does not match the type of the parent `CdcReport`. When the report references are recursed into, their references to `Organization` are nulled. Because the top-level report is also in this list of reports (as a reference to the same object), when `Organization` is set to null there, the top-level report also loses the reference. 

Perhaps this is another argument in favor of plain old DTOs instead of the action filter

**Comment by cailyncodes** [comment]
Closed by #960
