### ISSUE TITLE
Better api response transformation

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#939]
Development introduced: https://github.com/ctoec/ecis-experimental/issues/927 

the fix revealed another issue: https://github.com/ctoec/ecis-experimental/issues/938

which led to conversation around if the current solution for transforming API responses is meeting our needs. Summary of this conversation:
- Developers' experience debugging and modifying this code was not ideal -- it was confusing and unclear.
- This code does not work as initially expected: If an object is referenced multiple times in the object tree, all instances of it are modified when one is (i.e. if a field is nulled out on `Report.Organization.Reports[0]`, it will also be null on the top-level `Report`)
- Thus, this code does not address the implicit assumption that only properties that are Collections of previously seen types should be unset (as opposed to properties that are a single object of the previously seen type)

a proposal to simplify the necessary entity transformation:
- In the transform entity action filter, continue to handle setting/unsetting read-only properties
- Update db context to default to untracked mode
- In controller READ actions, return the result of the untracked query
- In controller WRITE actions:
    - figure out how to create/update the entity in the untracked db context
    - determine if entity ends up with unintended references. If it does, then will need to return result from the untracked query. Otherwise can just return the original entity

**Comment by cailyncodes** [comment]
Looks good to me!

**Comment by jlhogan** [comment]
https://github.com/dotnet/efcore/issues/11564 <- even with tracking turned off, entire nav properties (bi-directional relationship if defined that way) are loaded, which i think means this approach is no go.

work arounds:
- remove one half of the nav property relationship (not ideal b/c we want the flexibility of sometimes including one or the other)
- use annotations to skip in serialization (again, not ideal b/c we want the flexibility of sometimes including one or the other)
- Select anonymous object, then cast back to model type (have to write every field in the select query, prone to error when user adds new field)
and good old reliable...
- manually set relationships to null (what we're currently trying; complex and hard to understand + not very idiomatic. An attempt to simplify the existing solution to account for prev ignored implication that only arrays would be nulled out led to more typed being nulled than intended e.g. `enrollment.fundings` ends up being null because when `enrollment.fundings[0].enrollment` is processed, `fundings` is in the types to remove list and `enrollment.fundings[0].enrollment.fundings` get set to null, which is reflected back at the top-level `enrollment`) ((potential solution is to do this only to a certain level i.e. do not continue to recurse down when we see a type already in types to remove, and then have the json serializer loop detection handle those references))
- write custom json serializer
- DTOs

**Comment by jlhogan** [comment]
>     * ((potential solution is to do this only to a certain level i.e. do not continue to recurse down when we see a type already in types to remove, and then have the json serializer loop detection handle those references))
this works, but requires removing the read-only entities from the reference dict to avoid infinite recursing down the bidirectional nav property tree which ends up being SUPER slow (there may be a gotcha-ish reason for this tbd at some other hour) -- enrollments response was ~61KB, but client waited for >50sec (vs. master ~61KB, 300ms)

the problem-ness of the default, always populated nav properties makes a case for: 
- json serializer that could apply the existing transformations AFTER the self reference loops are dealt with
OR
- DTO

**Comment by jlhogan** [comment]
@cailyncodes  also did some exploring around potential solutions (will leave it to her to provide a summary of that if it seems like useful context to persist here!) and in the end we agreed to implement DTOs

**Comment by cailyncodes** [comment]
Closed by #952
