### ISSUE TITLE
Create backend integration tests for GET requests

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#940]
When we refactored from graphQL to dotnet MVC we lost integration test coverage in the backend. 

Add test coverage for full api calls, especially:
- api/Organizations/<orgId>
- - include=sites,funding_spaces
- api/organizations/<orgId>/Reports
- api/Organizations/<orgId>
- api/organizations/<orgId>/Enrollments
- - siteIds=<siteIds>, include=child,fundings,sites, startDate, endDate
- api/organizations/<orgId>/sites/<siteId>/Enrollments/<enrollmentId>
- - include=child,family,determinations,fundings,sites,past_enrollments
- api/organizations/<orgId>/Reports/<reportId>
- - include=organizations,enrollments,sites,funding_spaces,child

**Comment by jlhogan** [comment]
use NSwag to generate an openAPI client that has a constructor which takes HttpClient as constructor, to enable injection of the test client

**Comment by jlhogan** [comment]
seems nearly impossible to use nswag with dotnet core > 2.0 / on non-windows

**Comment by cailyncodes** [comment]
I think the way to go is to inject IHTTPClientFactory into the test startup file and retrive the factory class via the context and instantiate new clients in the test runs. (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1)

**Comment by jlhogan** [comment]
we already have test fixture to provide "apiHost", which exposes a Context for the backend, and a Client for sending requests to the backend

I was attempting to create OpenApi clients so we could avoid having to manually create the specific requests, but that was more trouble than it was worth given our set up.
