### ISSUE TITLE
DateInput can have today as helper text date

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#964]
- The helper text for creating and editing an income determination date uses today's date as an exmaple

**Comment by cailyncodes** [comment]
@jlhogan  Should we close this ticket from the PR you merged in or respecify the AC (actually setting today as det date) and move it to the backlog?

**Comment by jlhogan** [comment]
will respecify AC and move to backlog to be reprioritized in the future

**Comment by julyytran** [comment]
Decided we don't need to do this

**Comment by jlhogan** [comment]
I believe the current state in master is broken -- as in the defaults are there but don't work in the edit flow (there is no default for create flow). we should keep around a ticket to align app with AC (no default date)

**Comment by julyytran** [comment]
Got it, thank you. Updated and reopening this one, merging with #1090 and closing that one.
