### ISSUE TITLE
Add report roster to report detail view

### ISSUE THREAD

**Issue by julyytran** [ctoec/ecis-experimental#979]
[Mockups](https://app.abstract.com/share/f73a874c-697d-4f0e-bd37-fa167ecc2fa8?collectionId=f17f0f7e-9e6b-45f5-9e83-da84627e951d&collectionLayerId=82156b67-3de1-4adb-85f8-edc7b1589008&present=true&preview=false&sha=c72651e3fe6379138eea392d057a914a75506f7a)

When I click on a report that has not been submitted from the reports list, I land on the report roster. 

The report roster shows the roster, grouped by age group, for this report.

I see navigation tabs for the "Roster" and "Revenue". 
On each tab, I can either "Print report roster" or "Print report revenue", as it corresponds to the tab I am on.

**Comment by cailyncodes** [comment]
Closed by #1173
