### ISSUE TITLE
[Staging only] fam det edit form is expanded by defaut

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#985]
not reproducible in local dev

**Comment by RyanHansz** [comment]
<img width="1115" alt="Screen Shot 2020-04-27 at 10 10 11 AM" src="https://user-images.githubusercontent.com/63253539/80390254-2bc5ea80-887a-11ea-8925-75fe78391271.png">
Assume this is the same thing, so adding a screenshot here
