### ISSUE TITLE
Report columns aren't aligned

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/ecis-experimental#987]
In staging, the report columns appear to be center-aligned instead of left-aligned for text and right-aligned for numbers

**Comment by RyanHansz** [comment]
<img width="1005" alt="Screen Shot 2020-04-27 at 10 07 54 AM" src="https://user-images.githubusercontent.com/63253539/80390511-82cbbf80-887a-11ea-8ccd-511b042520a1.png">

**Comment by RyanHansz** [comment]
(Will attach design mockup shortly)

**Comment by cailyncodes** [comment]
Is this related to/different from https://github.com/ctoec/ecis-experimental/issues/891?

**Comment by RyanHansz** [comment]
@cailyncodes yes, same topic. I've adjusted it in this mockup by adding text-align:right to all the columns, but can't figure out how to get the $ to align.
<img width="937" alt="Screen Shot 2020-04-27 at 11 56 23 AM" src="https://user-images.githubusercontent.com/63253539/80393174-2074be00-887e-11ea-9cbb-79409947d752.png">

**Comment by cailyncodes** [comment]
The AC in #891 seems to be the same that the decimals points should line up (but the other ticket adds some more requirements). If the only thing is that the decimals points should line up (and it's the $0.00 column that's break that), I think there's a fix without worrying about the alignment. If it's that "Total (4 weeks)" slightly overhangs the values, I think that's a related but different fix then just changing the alignment, given how the same decimal place was implemented

**Comment by RyanHansz** [comment]
For more detail:
The data and column headers of utilization, reimbursement rate, total and Balance should have text-align: right property. As an example, I changed just the header and first row of balance in this mockup:

<img width="166" alt="Screen Shot 2020-04-27 at 2 04 21 PM" src="https://user-images.githubusercontent.com/63253539/80405013-06dc7200-8890-11ea-81e3-f9cb267cfbd5.png">

**Comment by cailyncodes** [comment]
Does the AC in the old ticket about the alignment of $ and ( no longer apply then?

**Comment by RyanHansz** [comment]
Yes, all the $ alignment still applies, just the data and column headers are right-aligned. (Thanks for dealing with me just noticing this now!)

**Comment by cailyncodes** [comment]
No worries! Just wanted to make sure we are on the same page :)

**Comment by cailyncodes** [comment]
![image](https://user-images.githubusercontent.com/16420449/80408195-cc290880-8894-11ea-9470-3aa100f1fe08.png)

Here's what it looks like with right align

**Comment by cailyncodes** [comment]
![image](https://user-images.githubusercontent.com/16420449/80408342-0b575980-8895-11ea-97a0-a3f168b3b971.png)

And here is without right align

**Comment by RyanHansz** [comment]
Right-aligned looks good!

**Comment by cailyncodes** [comment]
Okay cool - just wanted to make sure the extra space between utilization and reimbursement was expected with the right align. Thanks!
