### ISSUE TITLE
Update report status

### ISSUE THREAD

**Issue by julyytran** [ctoec/ecis-experimental#990]
[Mockups](https://app.abstract.com/share/f73a874c-697d-4f0e-bd37-fa167ecc2fa8?collectionId=f17f0f7e-9e6b-45f5-9e83-da84627e951d&collectionLayerId=82156b67-3de1-4adb-85f8-edc7b1589008&present=true&preview=false&sha=c72651e3fe6379138eea392d057a914a75506f7a)

- When I am viewing a report that is not submitted, I see "DRAFT" and the paper icon in the top right.

~~When I am viewing a report editing step (resolving overutilization or missing info), I see "EDITS" and the pencil icon in the top right. Blocked by #982 #983 #984~~

- When I am viewing a report detail page for a submitted report, the top right corner shows "SUBMITTED" and the paper icon with a background color of a light shade of success green (#ECF3EC)

**Comment by jlhogan** [comment]
Implementing DRAFT and SUBMITTED report status only
