### ISSUE TITLE
(Needs verified) Can't select contract space after attempting to save new enrollment

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#995]
(Needs verified) Can't select contract space after attempting to save the enrollment, then going back and filling in everything except that, then trying to save it

**Comment by RyanHansz** [comment]
Not sure if the same or different issue, but I started an incomplete enrollment which then didn't have any valid reporting periods to choose from. Filled in the needed info and reporting period still wasn't available. Eventually crashed when I tried submitting.
<img width="1085" alt="Screen Shot 2020-04-27 at 3 43 08 PM" src="https://user-images.githubusercontent.com/63253539/80413779-fb904300-889d-11ea-8949-51d529906172.png">
<img width="350" alt="Screen Shot 2020-04-27 at 3 42 57 PM" src="https://user-images.githubusercontent.com/63253539/80413781-fc28d980-889d-11ea-9b88-3a2cf61d4d35.png">

**Comment by RyanHansz** [comment]
Tried this again with all info entered and got the same result (no reporting period to choose from)
<img width="412" alt="Screen Shot 2020-04-27 at 3 46 10 PM" src="https://user-images.githubusercontent.com/63253539/80413966-4a3ddd00-889e-11ea-86c5-622b0eaff905.png">

**Comment by cailyncodes** [comment]
I'm not able to repo either of these. Can you share what values you put into what fields?

**Comment by RyanHansz** [comment]
The first reporting period appears if I select a date earlier than today (4/27) as the enrollment start date. Not sure if this is expected behavior or not.

**Comment by jlhogan** [comment]
likely a bug with the new reporting period options selection

**Comment by victoriasuwardiman** [comment]
Not sure if this is related too, but when I create an enrollment with Infant/Toddler, Full-Time, April 2020 and then go back to edit to change to Part-Time, that doesn't save. (No errors, just still shows as Full-Time)

**Comment by cailyncodes** [comment]
I have a fix for @victoriasuwardiman's comment. Still investigating others.

**Comment by cailyncodes** [comment]
I know what's up with @RyanHansz's second issue. Working on a fix.

**Comment by cailyncodes** [comment]
Fix for @RyanHansz's second issue done. I cannot repo the first issue. Looking now at @mmazanec22's issue (aka the main issue in this ticket)

**Comment by cailyncodes** [comment]
Oh I think @victoriasuwardiman's issue is the same as @mmazanec22's, which is now fixed. PR coming soon!
