### ISSUE TITLE
Switching funding to private pay removes CDC funding record from enrollment history

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/ecis-experimental#998]
1. Go to a child with CDC funding
2. Verify that "Switched to CDC - full time" is listed in enrollment history
3. Update Enrollment and funding section
4. Switch to private pay and save
5. Enrollment history now doesn't show "Switched to CDC - full time" or "Switched to private pay"

**Comment by cailyncodes** [comment]
I think this is because switching to private pay actually removes the CDC funding from the enrollment. Only withdrawing marks the funding as ended. I don't know if this is a bug or just a feature not yet implemented

**Comment by jlhogan** [comment]
>I don't know if this is a bug or just a feature not yet implemented
it is not yet implemented. Until we get to the "updated child actions" (https://github.com/ctoec/ecis-experimental/issues/844, now closed not sure why @julyytran ) and give the user the explicit options to edit or update fundings, they can only edit which means remove / add fundings, not end them. closing b/c this is a known limitation.

**Comment by julyytran** [comment]
We updated designs for this and are bringing to design review this week
