### ISSUE TITLE
(needs to be verified) Can't find withdrawn child in View Past Enrollments

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/ecis-experimental#999]
1. Go to a child's summary page
2. Withdraw
3. Set withdraw date to 04/01/2020
4. Confirm and withdraw
5. Go to roster --> site roster
6. View past enrollments
7. Set date to 03/27/2020 or date range to 03/01/2020 - 03/31/2020 and can't find the child

I maybe doing this wrong?

**Comment by cailyncodes** [comment]
This is a bug -- but it is related to the withdraw flow. It is setting the exit date the same as entry date. Probably also causing #993
